/** Merged into public/bible-map/data/locations.json via merge-bible-locations.mjs — same `id` overwrites. */

export const extra = [
  {
    id: "nineveh",
    name: "Nineveh",
    modernName: "Mosul area, Iraq",
    lat: 36.3594,
    lng: 43.1528,
    testament: ["OT"],
    era: ["divided-kingdom", "exile-return"],
    type: "city",
    description: "Assyrian imperial capital; Jonah’s preaching and Nahum’s oracle.",
    nameMeaning: "Akkadian Nina/Ninua (linked to a goddess); Hebrew Nineveh — exact etymology uncertain in Scripture.",
    events: ["Jonah’s mission", "Nahum’s prophecy of fall", "Sennacherib’s palace region"],
    scripture: [
      { ref: "Jonah 3:3", text: "Jonah obeyed the word of the Lord and went to Nineveh. Now Nineveh was a very large city; it took three days to go through it." },
      { ref: "Nahum 1:1", text: "A prophecy concerning Nineveh. The book of the vision of Nahum the Elkoshite." },
    ],
  },
  {
    id: "shechem",
    name: "Shechem",
    modernName: "Nablus area, West Bank",
    lat: 32.2139,
    lng: 35.2819,
    testament: ["OT", "NT"],
    era: ["patriarchs", "exodus-conquest", "united-kingdom", "divided-kingdom", "jesus-ministry"],
    type: "city",
    description: "Central highland city between Mount Ebal and Gerizim; covenant and well narratives; later Samaritan center.",
    nameMeaning: "Possibly “shoulder” (ridge between two heights).",
    events: ["Abram’s altar", "Dinah", "Joshua’s covenant", "Jesus and the woman at Sychar (nearby)"],
    scripture: [{ ref: "Genesis 12:6", text: "Abram traveled through the land as far as the site of the great tree of Moreh at Shechem. At that time the Canaanites were in the land." }],
  },
  {
    id: "bethel",
    name: "Bethel",
    modernName: "Beitin / Baytin area, West Bank",
    lat: 31.93,
    lng: 35.22,
    testament: ["OT"],
    era: ["patriarchs", "united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Jacob’s ‘house of God’ vision; later Jeroboam’s golden calves nearby.",
    nameMeaning: "Hebrew Beth-El = “house of God.”",
    events: ["Jacob’s ladder", "Ark at Bethel", "Jeroboam’s shrine"],
    scripture: [{ ref: "Genesis 28:19", text: "He called that place Bethel, though the city used to be called Luz." }],
  },
  {
    id: "shiloh",
    name: "Shiloh",
    modernName: "Khirbet Seilun, West Bank",
    lat: 32.056,
    lng: 35.289,
    testament: ["OT"],
    era: ["exodus-conquest", "united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Ephraimite sanctuary where the tabernacle and ark dwelt in the judges period.",
    nameMeaning: "Often understood as “rest” or “he who is sent.”",
    events: ["Hannah’s prayer", "Ark captured by Philistines"],
    scripture: [{ ref: "1 Samuel 1:3", text: "Year after year this man went up from his town to worship and sacrifice to the Lord Almighty at Shiloh, where Hophni and Phinehas, the two sons of Eli, were priests of the Lord." }],
  },
  {
    id: "gilgal",
    name: "Gilgal (Jordan crossing)",
    modernName: "Near Adam / Jordan River, Jordan",
    lat: 31.926,
    lng: 35.45,
    testament: ["OT"],
    era: ["exodus-conquest", "united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Israel’s first camp in Canaan; stones of memorial; prophetic associations.",
    nameMeaning: "Hebrew galal — “circle” of stones.",
    events: ["Stones from the Jordan", "Saul made king", "Elijah and Elisha"],
    scripture: [{ ref: "Joshua 4:19", text: "On the tenth day of the first month they camped at Gilgal on the eastern border of Jericho." }],
  },
  {
    id: "kadesh-barnea",
    name: "Kadesh Barnea",
    modernName: "Ein el-Qudeirat area, Negev",
    lat: 30.688,
    lng: 34.433,
    testament: ["OT"],
    era: ["exodus-conquest", "patriarchs"],
    type: "oasis",
    description: "Desert oasis of rebellion and spy mission launching point toward Canaan.",
    nameMeaning: "Kadesh = “holy”; Barnea likely a regional epithet.",
    events: ["Twelve spies", "Miriam’s death (region)"],
    scripture: [{ ref: "Numbers 13:26", text: "They came back to Moses and Aaron and the whole Israelite community at Kadesh in the Desert of Paran. There they reported to them and to the whole assembly and showed them the fruit of the land." }],
  },
  {
    id: "zoar",
    name: "Zoar",
    modernName: "Ghor as-Safi / southeast Dead Sea, Jordan",
    lat: 31.05,
    lng: 35.5,
    testament: ["OT"],
    era: ["patriarchs"],
    type: "city",
    description: "Small ‘town’ spared with Sodom and Gomorrah; Lot’s refuge.",
    nameMeaning: "Hebrew tsaar = “small” (Lot’s plea).",
    events: ["Lot escapes destruction"],
    scripture: [{ ref: "Genesis 19:22", text: "But flee there quickly, because I cannot do anything until you reach it. (That is why the town was called Zoar.)" }],
  },
  {
    id: "sodom",
    name: "Sodom (traditional region)",
    modernName: "South Dead Sea plain (debated)",
    lat: 31.08,
    lng: 35.42,
    testament: ["OT"],
    era: ["patriarchs"],
    type: "city",
    description: "Cities of the plain judged for wickedness alongside Gomorrah.",
    nameMeaning: "Uncertain; possibly linked to Hebrew sedeh / balloting or foreign root.",
    events: ["Angelic visitors", "Brimstone judgment"],
    scripture: [{ ref: "Genesis 19:24", text: "Then the Lord rained down burning sulfur on Sodom and Gomorrah—from the Lord out of the heavens." }],
  },
  {
    id: "debir",
    name: "Debir (Kiriath Sepher)",
    modernName: "Tell Beit Mirsim area, West Bank",
    lat: 31.41,
    lng: 34.98,
    testament: ["OT"],
    era: ["exodus-conquest", "united-kingdom"],
    type: "city",
    description: "Hill-country city taken in Joshua’s southern campaign; Othniel’s prize.",
    nameMeaning: "Debir = “sanctuary”; Kiriath Sepher = “city of books.”",
    events: ["Othniel captures Debir"],
    scripture: [{ ref: "Joshua 15:15", text: "From there, Judah attacked the people living in Debir (formerly called Kiriath Sepher)." }],
  },
  {
    id: "hazor",
    name: "Hazor",
    modernName: "Tell Hazor, Israel",
    lat: 33.0167,
    lng: 35.5681,
    testament: ["OT"],
    era: ["exodus-conquest", "united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Major Canaanite fortification north; burned in Joshua’s wars; Solomon chariot city.",
    nameMeaning: "Hebrew chatsor = “enclosed settlement / court.”",
    events: ["Jabin’s defeat", "Solomon’s district city"],
    scripture: [{ ref: "Joshua 11:10", text: "At that time Joshua turned back and captured Hazor and put its king to the sword. (Hazor had been the head of all these kingdoms.)" }],
  },
  {
    id: "lachish",
    name: "Lachish",
    modernName: "Tell ed-Duweir, Israel",
    lat: 31.564,
    lng: 34.85,
    testament: ["OT"],
    era: ["exodus-conquest", "united-kingdom", "divided-kingdom", "exile-return"],
    type: "city",
    description: "Fortified Judahite city; Assyrian reliefs show its siege.",
    nameMeaning: "Uncertain; possibly “invincible” (debated).",
    events: ["Amaziah captured", "Sennacherib’s siege"],
    scripture: [{ ref: "2 Kings 18:14", text: "King Hezekiah sent this message to the king of Assyria at Lachish: ‘I have done wrong. Withdraw from me, and I will pay whatever you demand of me.’" }],
  },
  {
    id: "megiddo",
    name: "Megiddo",
    modernName: "Tel Megiddo, Israel",
    lat: 32.5842,
    lng: 35.1821,
    testament: ["OT", "NT"],
    era: ["united-kingdom", "divided-kingdom", "second-temple"],
    type: "city",
    description: "Strategic Jezreel pass fortress; Josiah’s death; symbolic of final battle (Har-Magedon).",
    nameMeaning: "Possibly “place of troops / rendezvous.”",
    events: ["Solomon’s chariot city", "Josiah slain", "Armageddon imagery"],
    scripture: [{ ref: "2 Chronicles 35:22", text: "Josiah, however, would not turn away from him, but disguised himself to engage him in battle. He would not listen to what Necho had said at God’s command but went to fight him on the plain of Megiddo." }],
  },
  {
    id: "joppa",
    name: "Joppa (Jaffa)",
    modernName: "Jaffa, Tel Aviv, Israel",
    lat: 32.054,
    lng: 34.752,
    testament: ["OT", "NT"],
    era: ["united-kingdom", "second-temple", "early-church"],
    type: "city",
    description: "Ancient coastal port; cedar logs for Temple; Peter and Tabitha.",
    nameMeaning: "Greek Joppa from Hebrew Yapho — “beautiful.”",
    events: ["Cedars for Solomon", "Jonah’s ship", "Peter raises Dorcas"],
    scripture: [{ ref: "Acts 9:36", text: "In Joppa there was a disciple named Tabitha (in Greek her name is Dorcas); she was always doing good and helping the poor." }],
  },
  {
    id: "tyre",
    name: "Tyre",
    modernName: "Sur, Lebanon",
    lat: 33.27,
    lng: 35.195,
    testament: ["OT", "NT"],
    era: ["united-kingdom", "divided-kingdom", "exile-return", "second-temple", "jesus-ministry"],
    type: "city",
    description: "Phoenician maritime power; Tyrian purple; prophetic oracles; Jesus withdrew here.",
    nameMeaning: "Rock / crag (island and mainland harbors).",
    events: ["Hiram and Solomon", "Ezekiel’s lament", "Jesus in the region"],
    scripture: [{ ref: "Ezekiel 26:2", text: "Son of man, because Tyre has said of Jerusalem, ‘Aha! The gate to the nations is broken, and its doors have swung open to me; now that she lies in ruins I will prosper,’" }],
  },
  {
    id: "sidon",
    name: "Sidon",
    modernName: "Sayda, Lebanon",
    lat: 33.563,
    lng: 35.368,
    testament: ["OT", "NT"],
    era: ["patriarchs", "united-kingdom", "divided-kingdom", "jesus-ministry"],
    type: "city",
    description: "Northern Phoenician city; associated with Canaanite culture and Jesus’ ministry borders.",
    nameMeaning: "Tradition links to “fishing” or a founder Sidon.",
    events: ["Solomon’s timber", "Jesus in Tyre and Sidon region"],
    scripture: [{ ref: "Matthew 15:21", text: "Leaving that place, Jesus withdrew to the region of Tyre and Sidon." }],
  },
  {
    id: "gath",
    name: "Gath",
    modernName: "Tell es-Safi area, Israel",
    lat: 31.7,
    lng: 34.85,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Philistine pentapolis; Goliath’s hometown; David fled here.",
    nameMeaning: "Hebrew Gath = “wine press.”",
    events: ["David among Philistines", "Uzziah’s towers (region)"],
    scripture: [{ ref: "1 Samuel 17:4", text: "A champion named Goliath, who was from Gath, came out of the Philistine camp. His height was six cubits and a span." }],
  },
  {
    id: "ekron",
    name: "Ekron",
    modernName: "Tel Miqne, Israel",
    lat: 31.778,
    lng: 34.85,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Philistine border city; ark returned nearby.",
    nameMeaning: "Possibly “uprooted” or foreign root.",
    events: ["Ark to Beth Shemesh via Ekron"],
    scripture: [{ ref: "1 Samuel 5:10", text: "So they sent the ark of God to Ekron. As the ark of God was entering Ekron, the people of Ekron cried out, ‘They have brought the ark of the god of Israel around to us to kill us and our people.’" }],
  },
  {
    id: "ashdod",
    name: "Ashdod",
    modernName: "Ashdod, Israel",
    lat: 31.8044,
    lng: 34.6553,
    testament: ["OT", "NT"],
    era: ["united-kingdom", "divided-kingdom", "exile-return", "second-temple"],
    type: "city",
    description: "Philistine stronghold; Philistia’s plain power center.",
    nameMeaning: "Possibly “stronghold” or related to Ashdoda.",
    events: ["Philistine lords", "Nehemiah’s opponents"],
    scripture: [{ ref: "Nehemiah 13:23", text: "Moreover, in those days I saw men of Judah who had married women from Ashdod, Ammon and Moab." }],
  },
  {
    id: "gaza-city",
    name: "Gaza",
    modernName: "Gaza City, Palestine",
    lat: 31.5,
    lng: 34.4667,
    testament: ["OT", "NT"],
    era: ["patriarchs", "united-kingdom", "early-church"],
    type: "city",
    description: "Philistine pentapolis on the coast; Samson; Philip’s desert road.",
    nameMeaning: "Hebrew Azzah — “strong”; linked to treasury city.",
    events: ["Samson", "Philip and the Ethiopian"],
    scripture: [{ ref: "Acts 8:26", text: "Now an angel of the Lord said to Philip, ‘Go south to the road—the desert road—that goes down from Jerusalem to Gaza.’" }],
  },
  {
    id: "gezer",
    name: "Gezer",
    modernName: "Tel Gezer, Israel",
    lat: 31.877,
    lng: 34.922,
    testament: ["OT"],
    era: ["exodus-conquest", "united-kingdom"],
    type: "city",
    description: "Highland border fortress; Pharaoh gave it as a dowry city.",
    nameMeaning: "Possibly “portion” or “ridge.”",
    events: ["Horam defeated", "Solomon’s chariot city"],
    scripture: [{ ref: "1 Kings 9:15", text: "Here is the account of the forced labor King Solomon conscripted to build the Lord’s temple, his own palace, the terraces, the wall of Jerusalem, and Hazor, Megiddo and Gezer." }],
  },
  {
    id: "gibeah",
    name: "Gibeah of Benjamin",
    modernName: "Jaba / Tell el-Ful area, West Bank",
    lat: 31.85,
    lng: 35.22,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Benjaminite town; Levite’s concubine outrage; Saul’s home.",
    nameMeaning: "Hebrew gibeah = “hill.”",
    events: ["Outrage at Gibeah", "Saul anointed"],
    scripture: [{ ref: "1 Samuel 10:26", text: "Saul also went to his home in Gibeah, accompanied by valiant men whose hearts God had touched." }],
  },
  {
    id: "ramoth-gilead",
    name: "Ramoth in Gilead",
    modernName: "Reimun / Ramith area, Jordan",
    lat: 32.5,
    lng: 36.0,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Levitical city of refuge east of Jordan; Ahab’s death in battle.",
    nameMeaning: "Ramoth = “heights”; Gilead = rocky/hard region.",
    events: ["Jehoshaphat and Ahab’s campaign"],
    scripture: [{ ref: "1 Kings 22:20", text: "The Lord said, ‘Who will entice Ahab into attacking Ramoth Gilead and going to his death there?’" }],
  },
  {
    id: "dothan",
    name: "Dothan",
    modernName: "Tell Dotan, West Bank",
    lat: 32.425,
    lng: 35.2,
    testament: ["OT"],
    era: ["patriarchs", "divided-kingdom"],
    type: "city",
    description: "Joseph sold by brothers; Elisha’s surrounded servant.",
    nameMeaning: "Possibly “two wells.”",
    events: ["Joseph’s pit", "Chariots of fire"],
    scripture: [{ ref: "Genesis 37:17", text: "So Joseph went after his brothers and found them near Dothan. But they saw him in the distance, and before he reached them, they plotted to kill him." }],
  },
  {
    id: "anathoth",
    name: "Anathoth",
    modernName: "Anata, West Bank",
    lat: 31.81,
    lng: 35.26,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom", "exile-return"],
    type: "city",
    description: "Levitical town in Benjamin; Jeremiah’s hometown.",
    nameMeaning: "“Answers” or dedicated to Anath (debated).",
    events: ["Abiathar’s exile", "Jeremiah’s field"],
    scripture: [{ ref: "Jeremiah 1:1", text: "The words of Jeremiah son of Hilkiah, one of the priests at Anathoth in the territory of Benjamin." }],
  },
  {
    id: "rabbah-ammon",
    name: "Rabbah (Amman)",
    modernName: "Amman, Jordan",
    lat: 31.95,
    lng: 35.91,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom", "exile-return"],
    type: "city",
    description: "Capital of Ammon; Uriah’s death; later Philadelphia (Hellenistic).",
    nameMeaning: "Rabbah = “great (city).”",
    events: ["David and Bathsheba", "War with Ammon"],
    scripture: [{ ref: "2 Samuel 11:1", text: "In the spring, at the time when kings go off to war, David sent Joab out with the king’s men and the whole Israelite army. They destroyed the Ammonites and besieged Rabbah. But David remained in Jerusalem." }],
  },
  {
    id: "kir-hareseth",
    name: "Kir Hareseth",
    modernName: "Karak, Jordan",
    lat: 31.18,
    lng: 35.7,
    testament: ["OT"],
    era: ["divided-kingdom"],
    type: "city",
    description: "Moabite stronghold; Mesha’s revolt context.",
    nameMeaning: "Kir = wall; Hareseth = “pottery” / fortress sense.",
    events: ["Mesha’s sacrifice"],
    scripture: [{ ref: "2 Kings 3:25", text: "They destroyed the towns, and each man threw a stone on every good field until it was covered. They stopped up all the springs and cut down every good tree. Only Kir Hareseth was left with its stones in place, but men armed with slings surrounded it and attacked it." }],
  },
  {
    id: "hesbon",
    name: "Heshbon",
    modernName: "Hisban, Jordan",
    lat: 31.8,
    lng: 35.81,
    testament: ["OT"],
    era: ["exodus-conquest", "divided-kingdom", "exile-return"],
    type: "city",
    description: "Amorite then Moabite royal city east of the Jordan.",
    nameMeaning: "Possibly “stronghold” or “reckoning.”",
    events: ["Sihon defeated", "Prophetic taunts"],
    scripture: [{ ref: "Numbers 21:25", text: "Israel captured all the cities of the Amorites and occupied them, including Heshbon and all its surrounding settlements." }],
  },
  {
    id: "edom-region",
    name: "Edom (Seir)",
    modernName: "Southern Jordan / Negev highlands",
    lat: 30.3,
    lng: 35.6,
    testament: ["OT"],
    era: ["patriarchs", "exodus-conquest", "united-kingdom", "divided-kingdom", "exile-return"],
    type: "nation",
    description: "Esau’s descendants; rocky kingdom south and east of the Dead Sea.",
    nameMeaning: "Edom = “red” (Esau / stew).",
    events: ["Jacob and Esau", "Edom refuses Moses", "Herod Idumean line"],
    scripture: [{ ref: "Obadiah 1:1", text: "The vision of Obadiah. This is what the Sovereign Lord says about Edom—We have heard a message from the Lord: An envoy was sent to the nations to say, ‘Rise, let us go against her for battle’" }],
  },
  {
    id: "moab-region",
    name: "Moab",
    modernName: "Central Jordan plateau",
    lat: 31.5,
    lng: 35.8,
    testament: ["OT", "NT"],
    era: ["patriarchs", "exodus-conquest", "united-kingdom", "divided-kingdom", "exile-return", "jesus-ministry"],
    type: "nation",
    description: "Lot’s descendants east of the Dead Sea; Ruth’s story; Balak and Balaam.",
    nameMeaning: "From Lot’s son Moab — “from father” (ironic etymology in Gen 19:37).",
    events: ["Ruth and Naomi", "David’s parents (Ruth)", "John the Baptist’s wilderness"],
    scripture: [{ ref: "Ruth 1:1", text: "In the days when the judges ruled, there was a famine in the land. So a man from Bethlehem in Judah, together with his wife and two sons, went to live for a while in the country of Moab." }],
  },
  {
    id: "ammon-region",
    name: "Ammon",
    modernName: "North-central Jordan",
    lat: 32.0,
    lng: 36.0,
    testament: ["OT"],
    era: ["exodus-conquest", "united-kingdom", "divided-kingdom", "exile-return"],
    type: "nation",
    description: "Lot’s descendants through Ben-Ammi; frequent conflict and marriage tensions with Israel.",
    nameMeaning: "Ben-Ammi = “son of my people.”",
    events: ["Jephthah’s war", "Ammonite oppression"],
    scripture: [{ ref: "Judges 11:1", text: "Jephthah the Gileadite was a mighty warrior. He was the son of a prostitute, and his father Gilead." }],
  },
  {
    id: "philistia-region",
    name: "Philistia",
    modernName: "Gaza Strip coastal plain, Israel",
    lat: 31.65,
    lng: 34.65,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "nation",
    description: "Sea Peoples pentapolis league along the southern Levant coast.",
    nameMeaning: "Likely “land of sojourners” (Hebrew plishtim).",
    events: ["Samson", "Ark captured", "David’s wars"],
    scripture: [{ ref: "Judges 3:3", text: "These are the nations the Lord left to test all those Israelites who had not experienced any of the wars in Canaan — the five rulers of the Philistines, all the Canaanites, the Sidonians, and the Hivites living in the Lebanon mountains from Mount Baal Hermon to Lebo Hamath." }],
  },
  {
    id: "midian-region",
    name: "Midian",
    modernName: "Northwest Arabia / southern Jordan (schematic)",
    lat: 28.5,
    lng: 35.0,
    testament: ["OT"],
    era: ["patriarchs", "exodus-conquest"],
    type: "nation",
    description: "Ishmaelite-related peoples; Moses’ refuge; Gideon’s conflict.",
    nameMeaning: "From Midian son of Abraham and Keturah.",
    events: ["Moses flees", "Golden calf aftermath", "Gideon’s victory"],
    scripture: [{ ref: "Exodus 2:15", text: "When Pharaoh heard of this, he tried to kill Moses, but Moses fled from Pharaoh and went to live in Midian, where he sat down by a well." }],
  },
  {
    id: "susa",
    name: "Susa (Shushan)",
    modernName: "Shush, Iran",
    lat: 32.1892,
    lng: 48.2578,
    testament: ["OT"],
    era: ["exile-return"],
    type: "city",
    description: "Persian royal city; Esther and Daniel’s visions context.",
    nameMeaning: "City name from Elamite/Persian roots (lily / horse?).",
    events: ["Esther’s court", "Exiles in Persia"],
    scripture: [{ ref: "Esther 1:2", text: "At that time King Xerxes reigned from his royal throne in the citadel of Susa," }],
  },
  {
    id: "beth-shan",
    name: "Beth Shean",
    modernName: "Beit She’an, Israel",
    lat: 32.497,
    lng: 35.497,
    testament: ["OT"],
    era: ["exodus-conquest", "united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Strategic Jezreel junction; Philistines displayed Saul’s body.",
    nameMeaning: "Beth Shean = “house of quiet / rest.”",
    events: ["Saul’s body on the wall"],
    scripture: [{ ref: "1 Samuel 31:10", text: "They put his armor in the temple of the Ashtoreths and fastened his body to the wall of Beth Shan." }],
  },
  {
    id: "en-gedi",
    name: "En Gedi",
    modernName: "Ein Gedi nature reserve, Israel",
    lat: 31.45,
    lng: 35.39,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "oasis",
    description: "Dead Sea spring oasis where David hid from Saul.",
    nameMeaning: "Spring of the kid (young goat).",
    events: ["David spares Saul"],
    scripture: [{ ref: "1 Samuel 24:1", text: "After Saul returned from pursuing the Philistines, he was told, ‘David is in the Desert of En Gedi.’" }],
  },
  {
    id: "sychar",
    name: "Sychar (near Shechem)",
    modernName: "Askar / Nablus area, West Bank",
    lat: 32.224,
    lng: 35.268,
    testament: ["NT"],
    era: ["jesus-ministry"],
    type: "city",
    description: "Jacob’s well; Samaritan woman conversation.",
    nameMeaning: "Possibly linked to Shechem / “drunken” town (debated).",
    events: ["Jesus and the Samaritan woman"],
    scripture: [{ ref: "John 4:5", text: "So he came to a town in Samaria called Sychar, near the plot of ground Jacob had given to his son Joseph." }],
  },
  {
    id: "bethany",
    name: "Bethany",
    modernName: "Al-Eizariya, West Bank",
    lat: 31.771,
    lng: 35.262,
    testament: ["NT"],
    era: ["jesus-ministry"],
    type: "city",
    description: "Mary, Martha, and Lazarus; Jesus’ ascent toward Jerusalem.",
    nameMeaning: "Hebrew Beth Aniah — “house of the poor / affliction” (traditional).",
    events: ["Lazarus raised", "Anointing at Bethany"],
    scripture: [{ ref: "John 11:1", text: "Now a man named Lazarus was sick. He lived in Bethany, the village of Mary and her sister Martha." }],
  },
  {
    id: "bethphage",
    name: "Bethphage",
    modernName: "Mount of Olives east slope, Jerusalem",
    lat: 31.785,
    lng: 35.25,
    testament: ["NT"],
    era: ["jesus-ministry"],
    type: "village",
    description: "Starting point for Jesus’ Palm Sunday approach.",
    nameMeaning: "“House of unripe figs.”",
    events: ["Triumphal entry"],
    scripture: [{ ref: "Matthew 21:1", text: "As they approached Jerusalem and came to Bethphage on the Mount of Olives, Jesus sent two disciples," }],
  },
  {
    id: "emmaus",
    name: "Emmaus (Nicopolis tradition)",
    modernName: "Latrun / Abu Ghosh area (traditional), Israel",
    lat: 31.84,
    lng: 34.98,
    testament: ["NT"],
    era: ["jesus-ministry", "early-church"],
    type: "city",
    description: "Road where risen Jesus walked with disciples (site debated).",
    nameMeaning: "Possibly “warm springs.”",
    events: ["Road to Emmaus"],
    scripture: [{ ref: "Luke 24:13", text: "Now that same day two of them were going to a village called Emmaus, about seven miles from Jerusalem." }],
  },
  {
    id: "cana",
    name: "Cana of Galilee",
    modernName: "Kafr Kanna, Israel",
    lat: 32.749,
    lng: 35.344,
    testament: ["NT"],
    era: ["jesus-ministry"],
    type: "city",
    description: "Wedding at Cana; Nathanael’s hometown tradition.",
    nameMeaning: "Reed / nest (uncertain).",
    events: ["Water to wine"],
    scripture: [{ ref: "John 2:1", text: "On the third day a wedding took place at Cana in Galilee. Jesus’ mother was there," }],
  },
  {
    id: "nain",
    name: "Nain",
    modernName: "Nein, Israel",
    lat: 32.631,
    lng: 35.347,
    testament: ["NT"],
    era: ["jesus-ministry"],
    type: "city",
    description: "Galilean village; widow’s son raised.",
    nameMeaning: "Possibly “pleasant.”",
    events: ["Son raised from dead"],
    scripture: [{ ref: "Luke 7:11", text: "Soon afterward, Jesus went to a town called Nain, and his disciples and a large crowd went along with him." }],
  },
  {
    id: "tiberias",
    name: "Tiberias",
    modernName: "Tiberias, Israel",
    lat: 32.7959,
    lng: 35.531,
    testament: ["NT"],
    era: ["second-temple", "jesus-ministry"],
    type: "city",
    description: "Herodian capital on Galilee’s west shore; John’s Gospel uses the sea’s Roman name.",
    nameMeaning: "Named for Emperor Tiberius.",
    events: ["Lake commerce", "Resurrection breakfast region"],
    scripture: [{ ref: "John 6:23", text: "Then some boats from Tiberias landed near the place where the people had eaten the bread after the Lord had given thanks." }],
  },
  {
    id: "magdala",
    name: "Magdala",
    modernName: "Migdal, Israel",
    lat: 32.827,
    lng: 35.513,
    testament: ["NT"],
    era: ["jesus-ministry"],
    type: "city",
    description: "Fishing village; Mary Magdalene’s traditional home.",
    nameMeaning: "Tower (migdal).",
    events: ["Mary Magdalene follows Jesus"],
    scripture: [{ ref: "Luke 8:2", text: "Mary called Magdalene, from whom seven demons had come out;" }],
  },
  {
    id: "caesarea-philippi",
    name: "Caesarea Philippi (Banias)",
    modernName: "Banias, Golan Heights",
    lat: 33.248,
    lng: 35.694,
    testament: ["NT"],
    era: ["jesus-ministry"],
    type: "city",
    description: "Pan sanctuary region; Peter’s confession at ‘this rock.’",
    nameMeaning: "Caesar’s city of Philip (tetrarch).",
    events: ["Who do you say I am?"],
    scripture: [{ ref: "Matthew 16:13", text: "When Jesus came to the region of Caesarea Philippi, he asked his disciples, ‘Who do people say the Son of Man is?’" }],
  },
  {
    id: "bethsaida",
    name: "Bethsaida",
    modernName: "Et-Tell / el-Araj area, Israel",
    lat: 32.91,
    lng: 35.63,
    testament: ["NT"],
    era: ["jesus-ministry"],
    type: "city",
    description: "Fishing village; home of Philip, Andrew, Peter (tradition).",
    nameMeaning: "House of fishing / hunting.",
    events: ["Feeding the five thousand (nearby)", "Woes on Bethsaida"],
    scripture: [{ ref: "Matthew 11:21", text: "Woe to you, Chorazin! Woe to you, Bethsaida! For if the miracles that were performed in you had been performed in Tyre and Sidon, they would have repented long ago in sackcloth and ashes." }],
  },
  {
    id: "colossae",
    name: "Colossae",
    modernName: "Honaz area, Turkey",
    lat: 37.786,
    lng: 29.261,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Lycus valley city; letter to Colossians.",
    nameMeaning: "Giant / Colossus tradition (legendary).",
    events: ["Philemon’s church network"],
    scripture: [{ ref: "Colossians 1:2", text: "To God’s holy people in Colossae, the faithful brothers and sisters in Christ: Grace and peace to you from God our Father." }],
  },
  {
    id: "laodicea",
    name: "Laodicea",
    modernName: "Denizli area (ruins), Turkey",
    lat: 37.836,
    lng: 29.11,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Wealthy textile and banking city; one of the seven churches.",
    nameMeaning: "Laodicea = “justice of the people” (Seleucid name).",
    events: ["Lukewarm church"],
    scripture: [{ ref: "Revelation 3:14", text: "To the angel of the church in Laodicea write: These are the words of the Amen, the faithful and true witness, the ruler of God’s creation." }],
  },
  {
    id: "sardis",
    name: "Sardis",
    modernName: "Sart, Turkey",
    lat: 38.4883,
    lng: 28.0403,
    testament: ["OT", "NT"],
    era: ["exile-return", "early-church"],
    type: "city",
    description: "Lydian capital; dead reputation in Revelation.",
    nameMeaning: "Precious stone name tradition.",
    events: ["Croesus gold", "Letter to Sardis"],
    scripture: [{ ref: "Revelation 3:1", text: "These are the words of him who holds the seven spirits of God and the seven stars. I know your deeds; you have a reputation of being alive, but you are dead." }],
  },
  {
    id: "pergamon",
    name: "Pergamum",
    modernName: "Bergama, Turkey",
    lat: 39.1325,
    lng: 27.1844,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Royal Asian capital; altar imagery in Revelation.",
    nameMeaning: "Citadel / marriage of tribal names.",
    events: ["Seven churches"],
    scripture: [{ ref: "Revelation 2:12", text: "To the angel of the church in Pergamum write: These are the words of him who has the sharp, double-edged sword." }],
  },
  {
    id: "thyatira",
    name: "Thyatira",
    modernName: "Akhisar, Turkey",
    lat: 38.92,
    lng: 27.84,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Lydia’s hometown trade guilds; Jezebel teaching warned.",
    nameMeaning: "Sacrifice of labor / daughter names (uncertain).",
    events: ["Lydia’s purple trade", "Seven churches"],
    scripture: [{ ref: "Revelation 2:18", text: "To the angel of the church in Thyatira write: These are the words of the Son of God, whose eyes are like blazing fire and whose feet are like burnished bronze." }],
  },
  {
    id: "smyrna",
    name: "Smyrna",
    modernName: "İzmir, Turkey",
    lat: 38.4237,
    lng: 27.1428,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Wealthy port; Polycarp’s martyrdom tradition; suffering church.",
    nameMeaning: "Myrrh / fragrant spice (Greek Smyrna).",
    events: ["Seven churches", "Polycarp"],
    scripture: [{ ref: "Revelation 2:8", text: "To the angel of the church in Smyrna write: These are the words of him who is the First and the Last, who died and came to life again." }],
  },
  {
    id: "philadelphia-asia",
    name: "Philadelphia (Asia)",
    modernName: "Alaşehir, Turkey",
    lat: 38.35,
    lng: 28.517,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Missionary frontier city; ‘open door’ promise.",
    nameMeaning: "Brotherly love (Attalid royal name).",
    events: ["Seven churches"],
    scripture: [{ ref: "Revelation 3:7", text: "To the angel of the church in Philadelphia write: These are the words of him who is holy and true, who holds the key of David." }],
  },
  {
    id: "patmos",
    name: "Patmos",
    modernName: "Patmos, Greece",
    lat: 37.309,
    lng: 26.547,
    testament: ["NT"],
    era: ["early-church"],
    type: "island",
    description: "Volcanic island of John’s exile and Revelation.",
    nameMeaning: "Greek island name (uncertain origin).",
    events: ["Revelation vision"],
    scripture: [{ ref: "Revelation 1:9", text: "I, John, your brother and companion in the suffering and kingdom and patient endurance that are ours in Jesus, was on the island of Patmos because of the word of God and the testimony of Jesus." }],
  },
  {
    id: "miletos",
    name: "Miletus",
    modernName: "Milet, Turkey",
    lat: 37.53,
    lng: 27.28,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Paul’s farewell to Ephesian elders.",
    nameMeaning: "Ancient Anatolian city name.",
    events: ["Elders at Miletus"],
    scripture: [{ ref: "Acts 20:17", text: "From Miletus, Paul sent to Ephesus for the elders of the church." }],
  },
  {
    id: "troas",
    name: "Troas (Alexandria Troas)",
    modernName: "Dalyan, Turkey",
    lat: 39.75,
    lng: 26.15,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Paul’s vision of the Macedonian; Eutychus raised.",
    nameMeaning: "Trojan region refoundation.",
    events: ["Macedonian call", "Eutychus"],
    scripture: [{ ref: "Acts 16:8", text: "So they passed by Mysia and went down to Troas." }],
  },
  {
    id: "penuel",
    name: "Peniel (Penuel)",
    modernName: "Tell Deir Alla area, Jordan",
    lat: 32.2,
    lng: 35.6,
    testament: ["OT"],
    era: ["patriarchs", "divided-kingdom"],
    type: "city",
    description: "Jacob wrestled at the Jabbok ford; later Gideon story.",
    nameMeaning: "Face of God (Peniel).",
    events: ["Jacob wrestles", "Gideon"],
    scripture: [{ ref: "Genesis 32:30", text: "So Jacob called the place Peniel, saying, ‘It is because I saw God face to face, and yet my life was spared.’" }],
  },
  {
    id: "mizpah-gilead",
    name: "Mizpah in Gilead",
    modernName: "Tell Safut area, Jordan (schematic)",
    lat: 32.35,
    lng: 35.85,
    testament: ["OT"],
    era: ["divided-kingdom"],
    type: "city",
    description: "Jephthah’s assembly; watchtower name reused in many sites.",
    nameMeaning: "Watchtower / lookout (mizpah).",
    events: ["Jephthah’s vow"],
    scripture: [{ ref: "Judges 11:11", text: "So Jephthah went with the elders of Gilead, and the people made him head and commander over them. And he repeated all his words before the Lord in Mizpah." }],
  },
  {
    id: "jabesh-gilead",
    name: "Jabesh Gilead",
    modernName: "Tell el-Maqlub area, Jordan (schematic)",
    lat: 32.4,
    lng: 35.65,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "City that honored Saul’s bones.",
    nameMeaning: "Dry / drought (jabesh).",
    events: ["Saul’s rescue", "Burial of Saul"],
    scripture: [{ ref: "1 Samuel 11:1", text: "Nahash the Ammonite went up and besieged Jabesh Gilead. And all the men of Jabesh said to him, ‘Make a treaty with us, and we will be subject to you.’" }],
  },
  {
    id: "nob",
    name: "Nob",
    modernName: "Mount Scopus area, Jerusalem",
    lat: 31.8,
    lng: 35.24,
    testament: ["OT"],
    era: ["united-kingdom"],
    type: "city",
    description: "Priestly town massacred by Saul; David took Goliath’s sword.",
    nameMeaning: "Possibly “fruitfulness.”",
    events: ["Ahimelek helps David", "Saul’s massacre"],
    scripture: [{ ref: "1 Samuel 22:19", text: "Saul also attacked the priests, and the Lord put them to death for their complicity with David." }],
  },
  {
    id: "mahanaim",
    name: "Mahanaim",
    modernName: "Tell el-Dhibab area, Jordan",
    lat: 32.2,
    lng: 35.65,
    testament: ["OT"],
    era: ["patriarchs", "united-kingdom"],
    type: "city",
    description: "Jacob’s angel camp; Ishbosheth’s capital; Solomon district.",
    nameMeaning: "Two camps.",
    events: ["Jacob’s angels", "David flees Absalom"],
    scripture: [{ ref: "Genesis 32:2", text: "When Jacob saw them, he said, ‘This is the camp of God!’ So he named that place Mahanaim." }],
  },
  {
    id: "ziklag",
    name: "Ziklag",
    modernName: "Tell esh-Sharia / Negev (debated)",
    lat: 31.38,
    lng: 34.62,
    testament: ["OT"],
    era: ["united-kingdom"],
    type: "city",
    description: "Philistine border town given to David while he served Achish.",
    nameMeaning: "Possibly “pressing” or place-name of uncertain root.",
    events: ["David’s base", "Amalekite raid"],
    scripture: [{ ref: "1 Samuel 27:6", text: "So on that day Achish gave him Ziklag, and it has belonged to the kings of Judah ever since." }],
  },
  {
    id: "keilah",
    name: "Keilah",
    modernName: "Khirbet Qeila, West Bank",
    lat: 31.63,
    lng: 35.02,
    testament: ["OT"],
    era: ["united-kingdom"],
    type: "city",
    description: "Judahite fortified town where David rescued inhabitants from Philistines.",
    nameMeaning: "Fortress / gathering.",
    events: ["David saves Keilah"],
    scripture: [{ ref: "1 Samuel 23:2", text: "So David inquired of the Lord, ‘Shall I go and attack these Philistines?’ The Lord answered him, ‘Go, attack the Philistines and save Keilah.’" }],
  },
  {
    id: "hormah",
    name: "Hormah",
    modernName: "Tell Masos area, Negev",
    lat: 31.25,
    lng: 34.92,
    testament: ["OT"],
    era: ["exodus-conquest", "divided-kingdom"],
    type: "city",
    description: "Place devoted to destruction (‘hormah’) after early defeat and later conquest.",
    nameMeaning: "Ban / devoted thing.",
    events: ["Israel’s early defeat", "Later conquest"],
    scripture: [{ ref: "Numbers 21:3", text: "The Lord gave the Canaanites over to them, and they destroyed them and their towns; so the place was named Hormah." }],
  },
  {
    id: "kiriath-jearim",
    name: "Kiriath Jearim",
    modernName: "Deir el-Azar, Israel",
    lat: 31.771,
    lng: 35.107,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Benjamite border town where the ark stayed before David brought it to Jerusalem.",
    nameMeaning: "City of forests / Baalah.",
    events: ["Ark at Abinadab’s house"],
    scripture: [{ ref: "1 Samuel 7:1", text: "So the men of Kiriath Jearim came and took up the ark of the Lord. They brought it to Abinadab’s house on the hill and consecrated Eleazar his son to guard the ark of the Lord." }],
  },
  {
    id: "beth-horon",
    name: "Upper Beth Horon",
    modernName: "Beit Ur al-Foqa, West Bank",
    lat: 31.878,
    lng: 35.133,
    testament: ["OT"],
    era: ["exodus-conquest", "united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Strategic ascent to central highlands; Joshua’s long day battle linked to Aijalon valley.",
    nameMeaning: "House of Horon (deity name in Canaanite context).",
    events: ["Sun stands still (region)"],
    scripture: [{ ref: "Joshua 10:10", text: "The Lord threw them into confusion before Israel, so great a defeat at Gibeon that they fled from before Israel, toward the road to Beth Horon." }],
  },
  {
    id: "azekah",
    name: "Azekah",
    modernName: "Tell Zakariya, Israel",
    lat: 31.7,
    lng: 34.94,
    testament: ["OT"],
    era: ["exodus-conquest", "divided-kingdom"],
    type: "city",
    description: "Fortified Judahite city in the Shephelah; near David and Goliath’s valley.",
    nameMeaning: "Dug / earthwork (azekah).",
    events: ["Joshua’s southern campaign", "Siege of Lachish reliefs neighbor"],
    scripture: [{ ref: "Joshua 10:10", text: "The Lord threw them into confusion before Israel, so great a defeat at Gibeon that they fled from before Israel, toward the road to Beth Horon and Azekah and Makkedah." }],
  },
  {
    id: "socoh",
    name: "Socoh",
    modernName: "Khirbet Abbad, Israel",
    lat: 31.68,
    lng: 34.98,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Shephelah town overlooking Elah valley; Philistine muster against Saul.",
    nameMeaning: "Enclosed / hedge.",
    events: ["David and Goliath"],
    scripture: [{ ref: "1 Samuel 17:1", text: "Now the Philistines gathered their forces for war and assembled at Sokoh in Judah." }],
  },
  {
    id: "ramah-benjamin",
    name: "Ramah (Benjamin)",
    modernName: "er-Ram, West Bank",
    lat: 31.85,
    lng: 35.23,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom", "exile-return"],
    type: "city",
    description: "Benjaminite town north of Jerusalem; Samuel’s circuit; Jeremiah’s release.",
    nameMeaning: "Height / watch-height.",
    events: ["Samuel’s home", "Jeremiah’s chains removed"],
    scripture: [{ ref: "1 Samuel 7:17", text: "But he always went back to Ramah, where his home was, and there he also held court for Israel. And he built an altar there to the Lord." }],
  },
  {
    id: "tarshish",
    name: "Tarshish (trad. Spain)",
    modernName: "Cádiz region, Spain (schematic)",
    lat: 36.53,
    lng: -6.29,
    testament: ["OT"],
    era: ["divided-kingdom", "exile-return"],
    type: "nation",
    description: "Distant western port in prophetic imagination; Jonah fled toward Tarshish.",
    nameMeaning: "Uncertain; often linked to Tartessos in Spain.",
    events: ["Jonah’s ship", "Solomon’s ships with Hiram"],
    scripture: [{ ref: "Jonah 1:3", text: "But Jonah ran away from the Lord and headed for Tarshish. He went down to Joppa, where he found a ship bound for that port." }],
  },
  {
    id: "cush-region",
    name: "Cush (Upper Nile / Ethiopia)",
    modernName: "Sudan / northern Ethiopia (schematic)",
    lat: 16.5,
    lng: 33.5,
    testament: ["OT", "NT"],
    era: ["patriarchs", "united-kingdom", "divided-kingdom", "exile-return", "early-church"],
    type: "nation",
    description: "Biblical Cush south of Egypt; eunuch from Candace’s court.",
    nameMeaning: "Ethiopian region name (Cush son of Ham).",
    events: ["Moses’ Cushite wife (Num 12)", "Philip and the eunuch"],
    scripture: [{ ref: "Isaiah 18:1", text: "Woe to the land of whirring wings along the rivers of Cush," }],
  },
  {
    id: "put-libya",
    name: "Put (Libya)",
    modernName: "Cyrenaica, Libya (schematic)",
    lat: 32.5,
    lng: 22.5,
    testament: ["OT"],
    era: ["divided-kingdom", "exile-return"],
    type: "nation",
    description: "North African people listed with Cush and Lud in prophetic oracles.",
    nameMeaning: "Associated with Libyan peoples.",
    events: ["Ezekiel’s nations"],
    scripture: [{ ref: "Ezekiel 27:10", text: "Men of Persia, Lud and Put served as soldiers in your army." }],
  },
  {
    id: "lystra",
    name: "Lystra",
    modernName: "Hatunsaray, Turkey",
    lat: 37.59,
    lng: 32.35,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Galatian mission city; Paul stoned and left for dead.",
    nameMeaning: "Lycaonian city name.",
    events: ["Healing of cripple", "Paul stoned"],
    scripture: [{ ref: "Acts 14:8", text: "In Lystra there sat a man who was lame. He had been that way from birth and had never walked." }],
  },
  {
    id: "iconium",
    name: "Iconium",
    modernName: "Konya, Turkey",
    lat: 37.8667,
    lng: 32.4833,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Pauline mission in southern Galatia / Pisidian circuit.",
    nameMeaning: "Greek iconion — image city (legendary).",
    events: ["Paul and Barnabas flee"],
    scripture: [{ ref: "Acts 14:1", text: "At Iconium Paul and Barnabas went as usual into the Jewish synagogue. There they spoke so effectively that a great number of Jews and Greeks believed." }],
  },
  {
    id: "perga",
    name: "Perga",
    modernName: "Aksu, Antalya, Turkey",
    lat: 36.96,
    lng: 30.85,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Pamphylian capital; John Mark left Paul and Barnabas here.",
    nameMeaning: "Pamphylian royal city name.",
    events: ["First missionary journey"],
    scripture: [{ ref: "Acts 13:13", text: "From Paphos, Paul and his companions sailed to Perga in Pamphylia, where John left them to return to Jerusalem." }],
  },
  {
    id: "derbe",
    name: "Derbe",
    modernName: "Karaman area, Turkey (schematic)",
    lat: 37.35,
    lng: 33.3,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Eastern Lycaonian city visited on Paul’s journeys.",
    nameMeaning: "Place of juniper / thicket (traditional).",
    events: ["Paul’s return visit"],
    scripture: [{ ref: "Acts 14:20", text: "But after the disciples had gathered around him, he got up and went back into the city. The next day he and Barnabas left for Derbe." }],
  },
  {
    id: "salamis-cyprus",
    name: "Salamis (Cyprus)",
    modernName: "Famagusta area, Cyprus",
    lat: 35.18,
    lng: 33.9,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Cyprus port city; Paul and Barnabas preached in synagogues.",
    nameMeaning: "Named for Salamis the Greek hero (tradition).",
    events: ["John Mark assists", "Synagogue preaching"],
    scripture: [{ ref: "Acts 13:5", text: "When they arrived at Salamis, they proclaimed the word of God in the Jewish synagogues. John was with them as their helper." }],
  },
  {
    id: "tirzah",
    name: "Tirzah",
    modernName: "Tell el-Farah (North), West Bank",
    lat: 32.283,
    lng: 35.35,
    testament: ["OT"],
    era: ["divided-kingdom"],
    type: "city",
    description: "Early capital of northern kingdom before Samaria.",
    nameMeaning: "Delight / favorable.",
    events: ["Jeroboam’s capital", "Menahem"],
    scripture: [{ ref: "1 Kings 14:17", text: "Jeroboam’s wife arose and departed and came to Tirzah. As she came to the threshold of the house, the child died." }],
  },
  {
    id: "mount-hermon",
    name: "Mount Hermon",
    modernName: "Jabal el-Sheikh, Lebanon/Syria",
    lat: 33.4167,
    lng: 35.8667,
    testament: ["OT", "NT"],
    era: ["united-kingdom", "divided-kingdom", "jesus-ministry"],
    type: "mountain",
    description: "Anti-Lebanon snow peak; northern boundary imagery; Transfiguration tradition (region).",
    nameMeaning: "Forbidden / devoted (herem) or Semitic mountain deity echoes (debated).",
    events: ["Psalm 133 dew", "Caesarea Philippi region"],
    scripture: [{ ref: "Psalm 133:3", text: "It is as if the dew of Hermon were falling on Mount Zion. For there the Lord bestows his blessing, even life forevermore." }],
  },
  {
    id: "mount-tabor",
    name: "Mount Tabor",
    modernName: "Mount Tabor, Israel",
    lat: 32.687,
    lng: 35.39,
    testament: ["OT"],
    era: ["divided-kingdom"],
    type: "mountain",
    description: "Isolated Galilean hill; Deborah and Barak battle tradition.",
    nameMeaning: "Mound / navel of land.",
    events: ["Battle against Sisera"],
    scripture: [{ ref: "Judges 4:6", text: "She sent for Barak son of Abinoam from Kedesh in Naphtali and said to him, ‘The Lord, the God of Israel, commands you: “Go, take with you ten thousand men of Naphtali and Zebulun and lead them up to Mount Tabor.”’" }],
  },
  {
    id: "mount-gilboa",
    name: "Mount Gilboa",
    modernName: "Gilboa ridge, Israel",
    lat: 32.45,
    lng: 35.4,
    testament: ["OT"],
    era: ["united-kingdom"],
    type: "mountain",
    description: "Ridge where Saul and Jonathan died fighting Philistines.",
    nameMeaning: "Bubbling spring / boil?",
    events: ["Death of Saul"],
    scripture: [{ ref: "1 Samuel 31:1", text: "Now the Philistines fought against Israel; the Israelites fled before them, and many fell dead on Mount Gilboa." }],
  },
  {
    id: "mount-nebo",
    name: "Mount Nebo",
    modernName: "Mount Nebo, Jordan",
    lat: 31.72,
    lng: 35.72,
    testament: ["OT"],
    era: ["exodus-conquest"],
    type: "mountain",
    description: "Moses viewed the promised land; traditional burial site nearby.",
    nameMeaning: "Progeny / conquest (nebo).",
    events: ["Moses sees Canaan"],
    scripture: [{ ref: "Deuteronomy 34:1", text: "Then Moses climbed Mount Nebo from the plains of Moab to the top of Pisgah, across from Jericho. There the Lord showed him the whole land." }],
  },
  {
    id: "beer-lahai-roi",
    name: "Beer Lahai Roi",
    modernName: "Negev north (approximate)",
    lat: 31.15,
    lng: 34.45,
    testament: ["OT"],
    era: ["patriarchs"],
    type: "well",
    description: "Well where the angel met Hagar.",
    nameMeaning: "Well of the Living One who sees me.",
    events: ["Hagar’s encounter"],
    scripture: [{ ref: "Genesis 16:14", text: "That is why the well was called Beer Lahai Roi; it is still there, between Kadesh and Bered." }],
  },

  /* —— Levant micro-places —— */
  {
    id: "gibeon",
    name: "Gibeon",
    modernName: "Al Jib, West Bank",
    lat: 31.848,
    lng: 35.178,
    testament: ["OT"],
    era: ["exodus-conquest", "united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Hivite highland city famous for Joshua’s sun-standing battle and Solomon’s wisdom judgment.",
    nameMeaning: "Hill city (gibeah / height root).",
    events: ["Sun over Aijalon", "Solomon’s sword proposal"],
    scripture: [{ ref: "Joshua 10:12", text: "On the day the Lord gave the Amorites over to Israel, Joshua said to the Lord in the presence of Israel: ‘Sun, stand still over Gibeon, and you, moon, over the Valley of Aijalon.’" }],
  },
  {
    id: "mizpah-benjamin",
    name: "Mizpah (Benjamin)",
    modernName: "Tell en-Nasbeh / Nebi Samwil area (debated), West Bank",
    lat: 31.85,
    lng: 35.22,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom", "exile-return"],
    type: "city",
    description: "Benjaminite watch-height; often distinguished from Mizpah in Gilead.",
    nameMeaning: "Watchtower / lookout (mizpah).",
    events: ["Samuel judges Israel", "Ishmael at Mizpah"],
    scripture: [{ ref: "Judges 20:1", text: "Then all Israel from Dan to Beersheba and from the land of Gilead came together as one and assembled before the Lord in Mizpah." }],
  },
  {
    id: "adullam",
    name: "Adullam",
    modernName: "Khirbet el-Qom / Adullam region, Israel",
    lat: 31.65,
    lng: 34.97,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Shephelah town; David’s cave stronghold while fleeing Saul.",
    nameMeaning: "Possibly ‘justice of El’ or witness of El.",
    events: ["David’s cave", "Judah’s allotment"],
    scripture: [{ ref: "1 Samuel 22:1", text: "David left Gath and escaped to the cave of Adullam. When his brothers and his father’s household heard about it, they went down to him there." }],
  },
  {
    id: "en-rogel",
    name: "En Rogel",
    modernName: "Job’s Well / Bir Ayyub, Jerusalem",
    lat: 31.768,
    lng: 35.234,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "well",
    description: "Spring at the Kidron–Hinnom junction; spies and Adonijah’s rebellion.",
    nameMeaning: "Spring of the fuller / treaders (rogel).",
    events: ["Spies hide", "Adonijah’s feast"],
    scripture: [{ ref: "2 Samuel 17:17", text: "Both Jonathan and Ahimaaz stayed at En Rogel. A female servant was to go and inform them, and they were to go and tell King David, for they could not risk being seen entering the city." }],
  },
  {
    id: "tekoa",
    name: "Tekoa",
    modernName: "Tuqu‘, West Bank",
    lat: 31.652,
    lng: 35.173,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom", "exile-return"],
    type: "city",
    description: "Judahite hill town; home of the ‘wise woman’ and prophet Amos (tradition).",
    nameMeaning: "Trumpet / blast (teqa).",
    events: ["Joab’s ruse with wise woman", "Amos herdsman (tradition)"],
    scripture: [{ ref: "2 Samuel 14:2", text: "So Joab sent someone to Tekoa and had a wise woman brought from there. He said to her, ‘Pretend you are in mourning. Dress in mourning clothes, and don’t use any cosmetic lotions.’" }],
  },
  {
    id: "ziph-wilderness",
    name: "Wilderness of Ziph",
    modernName: "Hills southeast of Hebron, West Bank",
    lat: 31.48,
    lng: 35.18,
    testament: ["OT"],
    era: ["united-kingdom"],
    type: "wilderness",
    description: "Judean wilderness where David hid from Saul.",
    nameMeaning: "From the town Ziph (membrane / bottle?).",
    events: ["David eludes Saul"],
    scripture: [{ ref: "1 Samuel 23:14", text: "David stayed in the wilderness strongholds and in the hills of the Desert of Ziph. Day after day Saul searched for him, but God did not give David into his hands." }],
  },
  {
    id: "eshtaol",
    name: "Eshtaol",
    modernName: "Ishwa / Eshtaol, Israel",
    lat: 31.765,
    lng: 35.01,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Danite border town; Samson’s spirit stirred between here and Zorah.",
    nameMeaning: "Woman’s entreaty (traditional).",
    events: ["Samson’s story begins"],
    scripture: [{ ref: "Judges 13:25", text: "and the Spirit of the Lord began to stir him while he was in Mahaneh Dan, between Zorah and Eshtaol." }],
  },
  {
    id: "zorah",
    name: "Zorah",
    modernName: "Sar‘a, Israel",
    lat: 31.76,
    lng: 34.99,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Danite town; Manoah’s home and Samson’s upbringing.",
    nameMeaning: "Wasp / hornet (debated).",
    events: ["Samson’s birth announced"],
    scripture: [{ ref: "Judges 13:2", text: "A certain man of Zorah, named Manoah, from the clan of the Danites, had a wife who was childless, unable to give birth." }],
  },
  {
    id: "timnah-sorek",
    name: "Timnah (Sorek valley)",
    modernName: "Tel Batash / Timna, Israel",
    lat: 31.73,
    lng: 34.84,
    testament: ["OT"],
    era: ["divided-kingdom"],
    type: "city",
    description: "Philistine border town; Samson and Delilah narrative.",
    nameMeaning: "Portion / assigned (timnah).",
    events: ["Samson’s wife", "Delilah"],
    scripture: [{ ref: "Judges 16:4", text: "Some time later, he fell in love with a woman in the Valley of Sorek whose name was Delilah." }],
  },
  {
    id: "beth-zur",
    name: "Beth Zur",
    modernName: "Halhul area, West Bank",
    lat: 31.63,
    lng: 35.1,
    testament: ["OT"],
    era: ["united-kingdom", "second-temple"],
    type: "city",
    description: "Fortified ascent town guarding the Hebron–Jerusalem road; Maccabean wars.",
    nameMeaning: "House of the rock.",
    events: ["Judah’s border fortress", "Hasmonean campaigns"],
    scripture: [{ ref: "Joshua 15:58", text: "Halhul, Beth Zur, Gederah," }],
  },
  {
    id: "kedesh-naphtali",
    name: "Kedesh in Naphtali",
    modernName: "Tell Qedesh, Israel",
    lat: 33.11,
    lng: 35.53,
    testament: ["OT"],
    era: ["exodus-conquest", "divided-kingdom"],
    type: "city",
    description: "Levitical city of refuge in upper Galilee; Barak’s muster point.",
    nameMeaning: "Holy / sanctuary (qodesh).",
    events: ["Deborah summons Barak"],
    scripture: [{ ref: "Judges 4:6", text: "She sent for Barak son of Abinoam from Kedesh in Naphtali and said to him, ‘The Lord, the God of Israel, commands you: “Go, take with you ten thousand men of Naphtali and Zebulun and lead them up to Mount Tabor.”’" }],
  },
  {
    id: "ibleam",
    name: "Ibleam",
    modernName: "Khirbet Bel‘ameh, West Bank",
    lat: 32.55,
    lng: 35.32,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Jezreel corridor town; Ahaziah wounded fleeing Jehu.",
    nameMeaning: "People of destruction / mourning (uncertain).",
    events: ["Ahaziah’s flight"],
    scripture: [{ ref: "2 Kings 9:27", text: "When Ahaziah king of Judah saw what had happened, he fled up the road to Beth Haggan. Jehu chased him, shouting, ‘Kill him too!’" }],
  },
  {
    id: "endor",
    name: "Endor",
    modernName: "Ein Dor, Israel",
    lat: 32.656,
    lng: 35.237,
    testament: ["OT"],
    era: ["united-kingdom"],
    type: "village",
    description: "Jezreel foothill settlement; medium of Endor.",
    nameMeaning: "Spring of generation / Dor (uncertain).",
    events: ["Saul and the medium"],
    scripture: [{ ref: "1 Samuel 28:7", text: "Saul then said to his attendants, ‘Find me a woman who is a medium, so I may go and inquire of her.’ ‘There is one in Endor,’ they said." }],
  },
  {
    id: "taanach",
    name: "Taanach",
    modernName: "Ti‘innik, West Bank",
    lat: 32.51,
    lng: 35.21,
    testament: ["OT"],
    era: ["exodus-conquest", "divided-kingdom"],
    type: "city",
    description: "Canaanite town controlling Megiddo pass; Deborah’s victory.",
    nameMeaning: "Sandy / camp (uncertain).",
    events: ["Battle by waters of Megiddo"],
    scripture: [{ ref: "Judges 5:19", text: "Kings came, they fought, the kings of Canaan fought at Taanach by the waters of Megiddo, but they carried off no silver, no plunder." }],
  },
  {
    id: "dan-city",
    name: "Dan (Laish)",
    modernName: "Tell el-Qadi, Israel",
    lat: 33.248,
    lng: 35.602,
    testament: ["OT"],
    era: ["divided-kingdom"],
    type: "city",
    description: "Northernmost Israelite shrine; tribe migrated north and renamed Laish.",
    nameMeaning: "Judge / Dan son of Jacob.",
    events: ["Micah’s idols", "Jeroboam’s calves (tradition)"],
    scripture: [{ ref: "Judges 18:29", text: "They named it Dan after their ancestor Dan, who was born to Israel—though the city used to be called Laish." }],
  },
  {
    id: "abel-beth-maacah",
    name: "Abel Beth Maacah",
    modernName: "Tell Abil / Abil el-Qamh, Israel",
    lat: 33.268,
    lng: 35.585,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom"],
    type: "city",
    description: "Northern covenant city; Sheba’s head thrown over the wall.",
    nameMeaning: "Brook of the house of Maacah.",
    events: ["Wise woman saves city", "Sheba’s revolt"],
    scripture: [{ ref: "2 Samuel 20:14", text: "Sheba passed through all the tribes of Israel toward Abel Beth Maakah, through the entire region of the Bikrites, who gathered together and followed him." }],
  },
  {
    id: "succoth-jordan",
    name: "Succoth",
    modernName: "Deir Alla area, Jordan",
    lat: 32.2,
    lng: 35.6,
    testament: ["OT"],
    era: ["patriarchs", "exodus-conquest"],
    type: "city",
    description: "Transjordan settlement; Jacob builds booths; Gideon teaches elders.",
    nameMeaning: "Booths / shelters (succoth).",
    events: ["Jacob’s booths", "Gideon’s vengeance"],
    scripture: [{ ref: "Genesis 33:17", text: "Jacob, however, went to Sukkoth, where he built a place for himself and made shelters for his livestock. That is why the place is called Sukkoth." }],
  },
  {
    id: "abel-shittim",
    name: "Abel Shittim",
    modernName: "Tell el-Hammam / Shittim plains, Jordan",
    lat: 31.85,
    lng: 35.6,
    testament: ["OT"],
    era: ["exodus-conquest"],
    type: "oasis",
    description: "Moabite plains camp east of Jordan; Israel’s final stop before crossing.",
    nameMeaning: "Acacia meadow (shittim = acacia).",
    events: ["Balaam", "Moabite temptation"],
    scripture: [{ ref: "Numbers 33:49", text: "They camped on the Moabite plateau, along the Jordan across from Jericho between Beth Jeshimoth and Abel Shittim." }],
  },
  {
    id: "beth-horon-lower",
    name: "Lower Beth Horon",
    modernName: "Beit Ur at-Tahta, West Bank",
    lat: 31.87,
    lng: 35.12,
    testament: ["OT"],
    era: ["exodus-conquest", "divided-kingdom"],
    type: "city",
    description: "Ascent road town pair with Upper Beth Horon; Joshua’s battle.",
    nameMeaning: "House of Horon.",
    events: ["Amorite flight"],
    scripture: [{ ref: "Joshua 16:3", text: "went down westward to the territory of the Japhletites as far as the region of Lower Beth Horon and on to Gezer, which ended at the Mediterranean Sea." }],
  },
  {
    id: "ophel-jerusalem",
    name: "Ophel (Jerusalem ridge)",
    modernName: "Southern Temple Mount ridge, Jerusalem",
    lat: 31.775,
    lng: 35.235,
    testament: ["OT", "NT"],
    era: ["united-kingdom", "divided-kingdom", "exile-return", "second-temple"],
    type: "district",
    description: "Ridge south of the Temple; fortifications and Levitical dwellings.",
    nameMeaning: "Hill / swelling (ophel).",
    events: ["Jotham builds", "Nehemiah’s wall"],
    scripture: [{ ref: "2 Chronicles 27:3", text: "Jotham rebuilt the Upper Gate of the temple of the Lord and did extensive work on the wall at the hill of Ophel." }],
  },
  {
    id: "pool-of-siloam",
    name: "Pool of Siloam",
    modernName: "Siloam pool, Jerusalem",
    lat: 31.7758,
    lng: 35.2347,
    testament: ["OT", "NT"],
    era: ["divided-kingdom", "second-temple", "jesus-ministry"],
    type: "well",
    description: "Hezekiah’s tunnel outlet; Jesus sends blind man to wash.",
    nameMeaning: "Sent / commissioned (shiloah).",
    events: ["Hezekiah’s water works", "Blind man healed"],
    scripture: [{ ref: "John 9:7", text: "‘Go,’ he told him, ‘wash in the Pool of Siloam’ (this word means ‘Sent’). So the man went and washed, and came home seeing." }],
  },
  {
    id: "kidron-brook",
    name: "Kidron Valley",
    modernName: "Wadi an-Nar, Jerusalem",
    lat: 31.778,
    lng: 35.236,
    testament: ["OT", "NT"],
    era: ["united-kingdom", "divided-kingdom", "second-temple", "jesus-ministry"],
    type: "region",
    description: "Eastern ravine east of Jerusalem; David’s flight; Jesus crosses to Gethsemane.",
    nameMeaning: "Dark / gloomy (kidron).",
    events: ["David crosses fleeing Absalom", "Jesus to Gethsemane"],
    scripture: [{ ref: "John 18:1", text: "When he had finished praying, Jesus left with his disciples and crossed the Kidron Valley. On the other side there was a garden, and he and his disciples went into it." }],
  },
  {
    id: "lydda",
    name: "Lydda (Lod)",
    modernName: "Lod, Israel",
    lat: 32.001,
    lng: 34.888,
    testament: ["OT", "NT"],
    era: ["exile-return", "second-temple", "early-church"],
    type: "city",
    description: "Coastal plain town; Aeneas healed; NT Lydda.",
    nameMeaning: "Greek Lydda from Lod.",
    events: ["Peter heals Aeneas"],
    scripture: [{ ref: "Acts 9:32", text: "As Peter traveled about the country, he went to visit the Lord’s people who lived in Lydda." }],
  },
  {
    id: "antipatris",
    name: "Antipatris",
    modernName: "Rosh HaAyin / Aphek, Israel",
    lat: 32.1,
    lng: 34.94,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Herodian plain fortress; Paul escorted night march toward Caesarea.",
    nameMeaning: "Named for Herod Antipater.",
    events: ["Paul’s Roman custody transfer"],
    scripture: [{ ref: "Acts 23:31", text: "So the soldiers, carrying out their orders, took Paul with them during the night and brought him as far as Antipatris." }],
  },
  {
    id: "jarmuth",
    name: "Jarmuth",
    modernName: "Khirbet el-Yarmuk, Israel",
    lat: 31.71,
    lng: 34.89,
    testament: ["OT"],
    era: ["exodus-conquest"],
    type: "city",
    description: "Amorite royal city in Joshua’s southern coalition.",
    nameMeaning: "Height / exaltation.",
    events: ["Five kings at Makkedah"],
    scripture: [{ ref: "Joshua 10:5", text: "So the five kings of the Amorites—the kings of Jerusalem, Hebron, Jarmuth, Lachish and Eglon—joined forces, went up with all their troops and besieged Gibeon and attacked it." }],
  },
  {
    id: "shaaraim",
    name: "Shaaraim",
    modernName: "Khirbet Qeiyafa area (debated), Israel",
    lat: 31.69,
    lng: 34.96,
    testament: ["OT"],
    era: ["united-kingdom"],
    type: "city",
    description: "Shephelah town; Philistines fled toward it in David and Goliath narrative.",
    nameMeaning: "Two gates.",
    events: ["Philistine rout"],
    scripture: [{ ref: "1 Samuel 17:52", text: "Then the men of Israel and Judah surged forward with a shout and pursued the Philistines as far as Gath and Ekron, striking them down along the way to Shaaraim as far as Gath and Ekron." }],
  },
  {
    id: "beth-aven",
    name: "Bethel / Beth Aven",
    modernName: "Near Bethel, West Bank",
    lat: 31.94,
    lng: 35.22,
    testament: ["OT"],
    era: ["exodus-conquest", "divided-kingdom"],
    type: "city",
    description: "Border town name used prophetically for ‘house of trouble’ near Bethel.",
    nameMeaning: "House of vanity / trouble ( Hosea wordplay on Bethel).",
    events: ["Joshua’s border", "Hosea’s wordplay"],
    scripture: [{ ref: "Hosea 4:15", text: "Though you, Israel, commit adultery, do not let Judah become guilty. Do not go to Gilgal; do not go to Beth Aven. And do not swear, ‘As surely as the Lord lives!’" }],
  },
  {
    id: "michmash",
    name: "Michmash",
    modernName: "Mukhmas, West Bank",
    lat: 31.876,
    lng: 35.3,
    testament: ["OT"],
    era: ["united-kingdom"],
    type: "city",
    description: "Benjaminite gorge town; Jonathan’s daring raid.",
    nameMeaning: "Hidden / concealed.",
    events: ["Jonathan and armor-bearer"],
    scripture: [{ ref: "1 Samuel 14:5", text: "One cliff stood to the north toward Michmash, the other to the south toward Geba." }],
  },
  {
    id: "geba-benjamin",
    name: "Geba",
    modernName: "Jaba‘, West Bank",
    lat: 31.85,
    lng: 35.22,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom", "exile-return"],
    type: "city",
    description: "Benjaminite border fortress opposite Michmash.",
    nameMeaning: "Hill / height.",
    events: ["Saul’s muster", "Exiles return"],
    scripture: [{ ref: "1 Samuel 13:3", text: "Jonathan attacked the outpost at Geba, and the Philistines heard about it." }],
  },
  {
    id: "shunem",
    name: "Shunem",
    modernName: "Sulam, Israel",
    lat: 32.606,
    lng: 35.331,
    testament: ["OT"],
    era: ["divided-kingdom", "united-kingdom"],
    type: "city",
    description: "Jezreel ridge village; Elisha’s upper room and Shunammite woman.",
    nameMeaning: "Double resting (uncertain).",
    events: ["Elisha raises boy"],
    scripture: [{ ref: "2 Kings 4:8", text: "One day Elisha went to Shunem. And a well-to-do woman was there, who urged him to stay for a meal. So whenever he came by, he stopped there to eat." }],
  },
  {
    id: "en-gannim",
    name: "En Gannim",
    modernName: "Ein Ganim near Jenin (schematic), West Bank",
    lat: 32.46,
    lng: 35.3,
    testament: ["OT"],
    era: ["exodus-conquest", "divided-kingdom"],
    type: "city",
    description: "Border town in Issachar or allotment list; ‘spring of gardens.’",
    nameMeaning: "Spring of gardens.",
    events: ["Tribal boundary marker"],
    scripture: [{ ref: "Joshua 19:21", text: "Remeth, En Gannim, En Haddah and Beth Pazzez." }],
  },
  {
    id: "gerar",
    name: "Gerar",
    modernName: "Tell Haror / Negev (debated), Israel",
    lat: 31.4,
    lng: 34.6,
    testament: ["OT"],
    era: ["patriarchs", "united-kingdom"],
    type: "city",
    description: "Philistine border town of Abraham and Isaac sojourns.",
    nameMeaning: "Sojourning / lodging (uncertain).",
    events: ["Abraham and Abimelek", "Isaac’s wells"],
    scripture: [{ ref: "Genesis 26:1", text: "Now there was a famine in the land—besides the previous famine in Abraham’s time—and Isaac went to Abimelek king of the Philistines in Gerar." }],
  },
  {
    id: "beersheba-well",
    name: "Beersheba wells",
    modernName: "Tel Sheva, Israel",
    lat: 31.245,
    lng: 34.795,
    testament: ["OT"],
    era: ["patriarchs", "united-kingdom"],
    type: "well",
    description: "Oath wells between Abraham and Abimelek; southern anchor of ‘Dan to Beersheba.’",
    nameMeaning: "Well of the seven / well of the oath.",
    events: ["Covenant oath", "Elijah’s journey"],
    scripture: [{ ref: "Genesis 21:31", text: "So that place was called Beersheba, because the two men swore an oath there." }],
  },
  {
    id: "ashkelon-coast",
    name: "Ashkelon (coast)",
    modernName: "Tel Ashkelon, Israel",
    lat: 31.668,
    lng: 34.571,
    testament: ["OT"],
    era: ["united-kingdom", "divided-kingdom", "exile-return"],
    type: "city",
    description: "Philistine pentapolis on the sea; Samson’s riddle aftermath.",
    nameMeaning: "Migration / sojourning (uncertain).",
    events: ["Samson’s firebrands", "David laments Saul"],
    scripture: [{ ref: "2 Samuel 1:20", text: "Tell it not in Gath, proclaim it not in the streets of Ashkelon, lest the daughters of the Philistines be glad, lest the daughters of the uncircumcised triumph." }],
  },
  {
    id: "gibbethon",
    name: "Gibbethon",
    modernName: "Tell Malat, Israel",
    lat: 31.88,
    lng: 34.78,
    testament: ["OT"],
    era: ["divided-kingdom"],
    type: "city",
    description: "Philistine border town besieged by Israel; Nadab killed.",
    nameMeaning: "Mound / height.",
    events: ["Siege during Nadab’s reign"],
    scripture: [{ ref: "1 Kings 15:27", text: "Baasha son of Ahijah from the tribe of Issachar plotted against him, and he struck him down at Gibbethon, a Philistine town, while Nadab and all Israel were besieging it." }],
  },
  {
    id: "ramathaim",
    name: "Ramathaim (Zophim)",
    modernName: "Ar-Ram / Nabi Samwil area, West Bank",
    lat: 31.85,
    lng: 35.23,
    testament: ["OT"],
    era: ["united-kingdom"],
    type: "city",
    description: "Hill country of Ephraim; Samuel’s family hometown tradition.",
    nameMeaning: "Two heights of the Watchers (Zophim).",
    events: ["Elkanah’s yearly worship"],
    scripture: [{ ref: "1 Samuel 1:1", text: "There was a certain man from Ramathaim, a Zuphite from the hill country of Ephraim, whose name was Elkanah son of Jeroham, the son of Elihu, the son of Tohu, the son of Zuph, an Ephraimite." }],
  },
  {
    id: "jabneh-yavneh",
    name: "Jabneh (Jamnia)",
    modernName: "Yavne, Israel",
    lat: 31.876,
    lng: 34.739,
    testament: ["OT", "NT"],
    era: ["second-temple", "early-church"],
    type: "city",
    description: "Philistine border town; later rabbinic academy center post–AD 70.",
    nameMeaning: "God builds / causes to build.",
    events: ["Philistines capture ark camp", "Second Temple Judaism hub"],
    scripture: [{ ref: "2 Chronicles 26:6", text: "He went to war against the Philistines and broke down the walls of Gath, Jabneh and Ashdod. He then rebuilt towns near Ashdod and elsewhere among the Philistines." }],
  },

  /* —— Pauline Asia, Greece, Italy, Mediterranean —— */
  {
    id: "amphipolis",
    name: "Amphipolis",
    modernName: "Amfipoli, Greece",
    lat: 40.82,
    lng: 23.847,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Strategic bridge city on the Strymon; Paul passes through toward Thessalonica.",
    nameMeaning: "Around the city (amphi-polis).",
    events: ["Second missionary journey"],
    scripture: [{ ref: "Acts 17:1", text: "When Paul and his companions had passed through Amphipolis and Apollonia, they came to Thessalonica, where there was a Jewish synagogue." }],
  },
  {
    id: "apollonia-macedonia",
    name: "Apollonia (Macedonia)",
    modernName: "Vergia / Apollonia ad Axium, Greece",
    lat: 40.587,
    lng: 22.45,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Coastal waystation between Amphipolis and Thessalonica.",
    nameMeaning: "City of Apollo.",
    events: ["Paul’s journey"],
    scripture: [{ ref: "Acts 17:1", text: "When Paul and his companions had passed through Amphipolis and Apollonia, they came to Thessalonica, where there was a Jewish synagogue." }],
  },
  {
    id: "berea-macedonia",
    name: "Berea",
    modernName: "Veria, Greece",
    lat: 40.523,
    lng: 22.202,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Macedonian synagogue city; nobler reception of Scripture than Thessalonica.",
    nameMeaning: "Heavy / thick (place name).",
    events: ["Paul’s preaching", "Jason’s pursuit"],
    scripture: [{ ref: "Acts 17:11", text: "Now the Berean Jews were of more noble character than those in Thessalonica, for they received the message with great eagerness and examined the Scriptures every day to see if what Paul said was true." }],
  },
  {
    id: "cenchreae",
    name: "Cenchreae",
    modernName: "Kechries, Greece",
    lat: 37.884,
    lng: 23.121,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Corinth’s eastern harbor; Phoebe’s church and Paul’s hair vow.",
    nameMeaning: "From Greek Cenchreae (millet / plant name tradition).",
    events: ["Phoebe deacon", "Paul sails for Syria"],
    scripture: [{ ref: "Romans 16:1", text: "I commend to you our sister Phoebe, a deacon of the church in Cenchreae." }],
  },
  {
    id: "nicopolis-epirus",
    name: "Nicopolis",
    modernName: "Preveza area, Greece",
    lat: 38.96,
    lng: 20.73,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Augustan victory city; Paul wintered and planned ministry (tradition).",
    nameMeaning: "City of victory (Greek).",
    events: ["Paul’s winter (Titus 3:12 tradition)"],
    scripture: [{ ref: "Titus 3:12", text: "As soon as I send Artemas or Tychicus to you, do your best to come to me at Nicopolis, because I have decided to winter there." }],
  },
  {
    id: "hierapolis",
    name: "Hierapolis",
    modernName: "Pamukkale, Turkey",
    lat: 37.925,
    lng: 29.121,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Phrygian spa city above Laodicea; hot springs and Apollo/Lethe cults.",
    nameMeaning: "Holy city (Hierapolis).",
    events: ["Epaphras’s churches (Colossians)"],
    scripture: [{ ref: "Colossians 4:13", text: "I vouch for him that he is working hard for you and for those at Laodicea and Hierapolis." }],
  },
  {
    id: "apamea-phrygia",
    name: "Apamea (Phrygia)",
    modernName: "Dinar, Turkey",
    lat: 38.06,
    lng: 30.17,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Great inland market city on the royal road; Roman Asia assembly point.",
    nameMeaning: "Named for Seleucid queen Apama.",
    events: ["Jewish assembly in Phrygia (Acts)"],
    scripture: [{ ref: "Acts 16:6", text: "Paul and his companions traveled throughout the region of Phrygia and Galatia, having been kept by the Holy Spirit from preaching the word in the province of Asia." }],
  },
  {
    id: "patara",
    name: "Patara",
    modernName: "Gelemiş, Turkey",
    lat: 36.26,
    lng: 29.316,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Lycian harbor; Paul changes ships for Tyre.",
    nameMeaning: "Lycian port name.",
    events: ["Paul finds ship to Phoenicia"],
    scripture: [{ ref: "Acts 21:1", text: "After we had torn ourselves away from them, we put out to sea and sailed straight to Cos. The next day we went to Rhodes and from there to Patara." }],
  },
  {
    id: "myra",
    name: "Myra",
    modernName: "Demre, Turkey",
    lat: 36.244,
    lng: 29.985,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Lycian capital port; centurion’s Alexandrian grain ship.",
    nameMeaning: "Myrrh / fragrant resin (folk etymology).",
    events: ["Paul’s custody voyage"],
    scripture: [{ ref: "Acts 27:5", text: "When we had sailed across the open sea off the coast of Cilicia and Pamphylia, we landed at Myra in Lycia." }],
  },
  {
    id: "rhodes",
    name: "Rhodes",
    modernName: "Rhodes, Greece",
    lat: 36.434,
    lng: 28.217,
    testament: ["NT"],
    era: ["early-church"],
    type: "island",
    description: "Dodecanese island; Paul’s return voyage touches here.",
    nameMeaning: "Rose (Greek rhodon).",
    events: ["Return journey"],
    scripture: [{ ref: "Acts 21:1", text: "After we had torn ourselves away from them, we put out to sea and sailed straight to Cos. The next day we went to Rhodes and from there to Patara." }],
  },
  {
    id: "cnidus",
    name: "Cnidus",
    modernName: "Datça peninsula, Turkey",
    lat: 36.685,
    lng: 27.373,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Carian peninsula city; storm voyage rounds here.",
    nameMeaning: "Nettle / thorn place (traditional).",
    events: ["Paul’s ship tacks southwest"],
    scripture: [{ ref: "Acts 27:7", text: "We moved about slowly for many days and had difficulty arriving off Cnidus. When the wind did not allow us to hold our course, we sailed to the lee of Crete opposite Salmone." }],
  },
  {
    id: "cos-island",
    name: "Cos (Kos)",
    modernName: "Kos, Greece",
    lat: 36.893,
    lng: 27.288,
    testament: ["NT"],
    era: ["early-church"],
    type: "island",
    description: "Asclepius cult island; Paul’s voyage toward Rhodes.",
    nameMeaning: "Island name (pre-Greek?).",
    events: ["Return leg of journey"],
    scripture: [{ ref: "Acts 21:1", text: "After we had torn ourselves away from them, we put out to sea and sailed straight to Cos. The next day we went to Rhodes and from there to Patara." }],
  },
  {
    id: "fair-havens-crete",
    name: "Fair Havens (Crete)",
    modernName: "Kali Limenes, Greece",
    lat: 34.92,
    lng: 24.78,
    testament: ["NT"],
    era: ["early-church"],
    type: "harbor",
    description: "South Cretan roadstead where the centurion’s ship waited before the storm.",
    nameMeaning: "Good harbors (Kaloi Limenes).",
    events: ["Paul warns against sailing"],
    scripture: [{ ref: "Acts 27:8", text: "We moved along the coast with difficulty and came to a place called Fair Havens, near the town of Lasea." }],
  },
  {
    id: "phoenix-crete",
    name: "Phoenix (Crete)",
    modernName: "Phoenix / Lutro area (traditional), Greece",
    lat: 35.2,
    lng: 24.08,
    testament: ["NT"],
    era: ["early-church"],
    type: "harbor",
    description: "Winter harbor goal that Paul’s ship never reached before the gale.",
    nameMeaning: "Date palm / Phoenician (traditional).",
    events: ["Storm decision"],
    scripture: [{ ref: "Acts 27:12", text: "Since the harbor was unsuitable to winter in, the majority decided that we should sail on, hoping to reach Phoenix and winter there. This was a harbor in Crete, facing both southwest and northwest." }],
  },
  {
    id: "malta-melita",
    name: "Malta (Melita)",
    modernName: "Malta",
    lat: 35.937,
    lng: 14.375,
    testament: ["NT"],
    era: ["early-church"],
    type: "island",
    description: "Shipwreck island; Publius’s father healed.",
    nameMeaning: "Honey (meli) folk etymology; island name Latin Melita.",
    events: ["Shipwreck", "Publius"],
    scripture: [{ ref: "Acts 28:1", text: "Once safely on shore, we found out that the island was called Malta." }],
  },
  {
    id: "syracuse",
    name: "Syracuse",
    modernName: "Siracusa, Italy",
    lat: 37.075,
    lng: 15.286,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Sicilian Greek powerhouse; Paul’s Alexandrian ship put in.",
    nameMeaning: "Syracuse (Sicel/Spring myths).",
    events: ["Three-day stay"],
    scripture: [{ ref: "Acts 28:12", text: "We put in at Syracuse and stayed there three days." }],
  },
  {
    id: "puteoli",
    name: "Puteoli",
    modernName: "Pozzuoli, Italy",
    lat: 40.832,
    lng: 14.121,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Bay of Naples harbor where Roman Christians met Paul’s ship.",
    nameMeaning: "Little wells (Latin putei).",
    events: ["Brothers greet Paul"],
    scripture: [{ ref: "Acts 28:13", text: "From there we set sail and arrived at Rhegium. The next day the south wind came up, and on the following day we reached Puteoli." }],
  },
  {
    id: "appii-forum",
    name: "Forum of Appius",
    modernName: "Latina area, Italy",
    lat: 41.45,
    lng: 13.05,
    testament: ["NT"],
    era: ["early-church"],
    type: "road-station",
    description: "Market town on the Appian Way south of Rome; Christians met Paul.",
    nameMeaning: "Market of Appius Claudius.",
    events: ["Paul approaches Rome"],
    scripture: [{ ref: "Acts 28:15", text: "The brothers and sisters there had heard that we were coming, and they traveled as far as the Forum of Appius and the Three Taverns to meet us." }],
  },
  {
    id: "three-taverns",
    name: "Three Taverns",
    modernName: "Tre Fontane area (traditional), Italy",
    lat: 41.78,
    lng: 12.62,
    testament: ["NT"],
    era: ["early-church"],
    type: "road-station",
    description: "Appian Way stop closer to Rome; second welcoming party.",
    nameMeaning: "Latin Tres Tabernae — three shops / inns.",
    events: ["Paul encouraged en route to Rome"],
    scripture: [{ ref: "Acts 28:15", text: "At the sight of these people Paul thanked God and was encouraged." }],
  },
  {
    id: "dyrrachium",
    name: "Dyrrachium (Epirus)",
    modernName: "Durrës, Albania",
    lat: 41.323,
    lng: 19.441,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Adriatic port opposite Brundisium; Illyricum mission horizon.",
    nameMeaning: "Epidamnos renamed for Rome (Dyrrachium).",
    events: ["East–west travel corridor"],
    scripture: [{ ref: "Romans 15:19", text: "So from Jerusalem all the way around to Illyricum, I have fully proclaimed the gospel of Christ." }],
  },
  {
    id: "assos",
    name: "Assos",
    modernName: "Behramkale, Turkey",
    lat: 39.487,
    lng: 26.336,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Troad harbor; Paul walked overland while Luke sailed.",
    nameMeaning: "Latin Assos from Greek.",
    events: ["Paul rejoins ship"],
    scripture: [{ ref: "Acts 20:13", text: "We went on ahead to the ship and sailed for Assos, where we were going to take Paul aboard. He had made this arrangement because he was going there on foot." }],
  },
  {
    id: "adramyttium",
    name: "Adramyttium",
    modernName: "Edremit, Turkey",
    lat: 39.592,
    lng: 27.02,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Mysian port; ship of Adramyttium in custody voyage.",
    nameMeaning: "Named for Adramys (mythic founder).",
    events: ["Coastal shipping"],
    scripture: [{ ref: "Acts 27:2", text: "We boarded a ship from Adramyttium about to sail for ports along the coast of the province of Asia, and we put out to sea. Aristarchus, a Macedonian from Thessalonica, was with us." }],
  },
  {
    id: "phaselis",
    name: "Phaselis",
    modernName: "Tekirova, Turkey",
    lat: 36.52,
    lng: 30.53,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Lycian harbor city on Pamphylian coast; possible coasting point.",
    nameMeaning: "Bay of date palms (traditional).",
    events: ["Roman-era maritime traffic"],
    scripture: [{ ref: "Acts 27:5", text: "When we had sailed across the open sea off the coast of Cilicia and Pamphylia, we landed at Myra in Lycia." }],
  },
  {
    id: "brundisium",
    name: "Brundisium",
    modernName: "Brindisi, Italy",
    lat: 40.632,
    lng: 17.942,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Heel-of-Italy port paired with Dyrrachium on the Ignatian/Appian corridor.",
    nameMeaning: "Deer’s head (Brundisium folk etymology).",
    events: ["Roman grain fleet routes"],
    scripture: [{ ref: "Acts 27:1", text: "When it was decided that we would sail for Italy, Paul and some other prisoners were handed over to a centurion named Julius, who belonged to the Imperial Regiment." }],
  },
  {
    id: "regium",
    name: "Rhegium (Regium)",
    modernName: "Reggio Calabria, Italy",
    lat: 38.111,
    lng: 15.647,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Strait of Messina toehold; Paul waits for favorable wind to Puteoli.",
    nameMeaning: "Breakwater / cape (Greek Rhegion).",
    events: ["South wind to Italy"],
    scripture: [{ ref: "Acts 28:13", text: "From there we set sail and arrived at Rhegium. The next day the south wind came up, and on the following day we reached Puteoli." }],
  },
  {
    id: "gortyna-crete",
    name: "Gortyna",
    modernName: "Gortyn, Crete, Greece",
    lat: 35.068,
    lng: 24.947,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Roman capital of Crete; Titus left to set elders in every town.",
    nameMeaning: "Cretan royal city name.",
    events: ["Titus on Crete"],
    scripture: [{ ref: "Titus 1:5", text: "The reason I left you in Crete was that you might put in order what was left unfinished and appoint elders in every town, as I directed you." }],
  },
  {
    id: "philippi-neapolis",
    name: "Neapolis (Macedonia)",
    modernName: "Kavala, Greece",
    lat: 40.939,
    lng: 24.406,
    testament: ["NT"],
    era: ["early-church"],
    type: "city",
    description: "Harbor where Paul first set foot in Europe before Philippi.",
    nameMeaning: "New city (Greek).",
    events: ["Paul crosses into Macedonia"],
    scripture: [{ ref: "Acts 16:11", text: "From Troas we put out to sea and sailed straight for Samothrace, and the next day we went to Neapolis." }],
  },
  {
    id: "samothrace",
    name: "Samothrace",
    modernName: "Samothraki, Greece",
    lat: 40.474,
    lng: 25.522,
    testament: ["NT"],
    era: ["early-church"],
    type: "island",
    description: "Aegean island cult center of Cabeiri; Paul’s overnight stop.",
    nameMeaning: "Thracian sacred island.",
    events: ["Voyage to Neapolis"],
    scripture: [{ ref: "Acts 16:11", text: "From Troas we put out to sea and sailed straight for Samothrace, and the next day we went to Neapolis." }],
  },
  {
    id: "chios",
    name: "Chios",
    modernName: "Chios, Greece",
    lat: 38.368,
    lng: 26.135,
    testament: ["NT"],
    era: ["early-church"],
    type: "island",
    description: "Aegean island; Paul’s return toward Miletus.",
    nameMeaning: "Snow (Greek chion) folk etymology.",
    events: ["Coasting voyage"],
    scripture: [{ ref: "Acts 20:15", text: "Sailing from there, we arrived the next day opposite Chios. The day after that we crossed over to Samos, and on the following day arrived at Miletus." }],
  },
  {
    id: "samos",
    name: "Samos",
    modernName: "Samos, Greece",
    lat: 37.754,
    lng: 26.976,
    testament: ["NT"],
    era: ["early-church"],
    type: "island",
    description: "Hera cult island off Ephesus; Paul passes opposite.",
    nameMeaning: "Height / lofty (traditional).",
    events: ["Return voyage"],
    scripture: [{ ref: "Acts 20:15", text: "Sailing from there, we arrived the next day opposite Chios. The day after that we crossed over to Samos, and on the following day arrived at Miletus." }],
  },
];
