export type GospelKey = "matthew" | "mark" | "luke" | "john";

export type ParallelSection = {
  id: number;
  group: string;
  title: string;
  refs: Record<GospelKey, string | null>;
  note?: string;
};

const NR = null;

export const PARALLEL_GOSPEL_SECTIONS: ParallelSection[] = [
  { id: 1, group: "Pre-Christ Narratives", title: "Before the Beginning", refs: { matthew: NR, mark: NR, luke: "Luke 1:1-4", john: "John 1:1-14" } },
  { id: 2, group: "Birth and Early Childhood", title: "The Birth of John the Baptist Foretold", refs: { matthew: NR, mark: NR, luke: "Luke 1:5-25", john: NR } },
  { id: 3, group: "Birth and Early Childhood", title: "The Annunciation", refs: { matthew: NR, mark: NR, luke: "Luke 1:26-38", john: NR } },
  { id: 4, group: "Birth and Early Childhood", title: "Mary Visits Elizabeth", refs: { matthew: NR, mark: NR, luke: "Luke 1:39-56", john: NR } },
  { id: 5, group: "Birth and Early Childhood", title: "Birth of John the Baptist", refs: { matthew: NR, mark: NR, luke: "Luke 1:57-80", john: NR } },
  { id: 6, group: "Birth and Early Childhood", title: "The Two Genealogies", refs: { matthew: "Matthew 1:1-17", mark: NR, luke: "Luke 3:23-38", john: NR } },
  { id: 7, group: "Birth and Early Childhood", title: "The Birth of Jesus Christ", refs: { matthew: "Matthew 1:18-25", mark: NR, luke: "Luke 2:1-7", john: NR } },
  { id: 8, group: "Birth and Early Childhood", title: "The Shepherds", refs: { matthew: NR, mark: NR, luke: "Luke 2:8-20", john: NR } },
  { id: 9, group: "Birth and Early Childhood", title: "Presentation in the Temple", refs: { matthew: NR, mark: NR, luke: "Luke 2:21-38", john: NR } },
  { id: 10, group: "Birth and Early Childhood", title: "The Wise Men", refs: { matthew: "Matthew 2:1-12", mark: NR, luke: NR, john: NR } },
  { id: 11, group: "Birth and Early Childhood", title: "Flight into Egypt / Return to Nazareth", refs: { matthew: "Matthew 2:13-23", mark: NR, luke: "Luke 2:39", john: NR } },
  { id: 12, group: "Birth and Early Childhood", title: "Jesus at Age 12 in the Temple", refs: { matthew: NR, mark: NR, luke: "Luke 2:40-52", john: NR } },
  { id: 13, group: "Beginning of Ministry", title: "Ministry of John the Baptist", refs: { matthew: "Matthew 3:1-12", mark: "Mark 1:1-8", luke: "Luke 3:1-18", john: "John 1:15-31" } },
  { id: 14, group: "Beginning of Ministry", title: "Baptism of Jesus", refs: { matthew: "Matthew 3:13-17", mark: "Mark 1:9-11", luke: "Luke 3:21-22", john: "John 1:32-34" } },
  { id: 15, group: "Beginning of Ministry", title: "The Temptation", refs: { matthew: "Matthew 4:1-11", mark: "Mark 1:12-13", luke: "Luke 4:1-13", john: NR } },
  { id: 16, group: "Beginning of Ministry", title: "First Disciples Called", refs: { matthew: NR, mark: NR, luke: NR, john: "John 1:35-51" } },
  { id: 17, group: "Beginning of Ministry", title: "Wedding at Cana", refs: { matthew: NR, mark: NR, luke: NR, john: "John 2:1-11" } },
  { id: 18, group: "Beginning of Ministry", title: "Cleansing the Temple (First)", refs: { matthew: NR, mark: NR, luke: NR, john: "John 2:12-25" } },
  { id: 19, group: "Beginning of Ministry", title: "Nicodemus", refs: { matthew: NR, mark: NR, luke: NR, john: "John 3:1-21" } },
  { id: 20, group: "Beginning of Ministry", title: "Woman at the Well", refs: { matthew: NR, mark: NR, luke: NR, john: "John 4:3-42" } },
  { id: 21, group: "Beginning of Ministry", title: "Return to Galilee", refs: { matthew: "Matthew 4:12", mark: "Mark 1:14-15", luke: "Luke 4:14-15", john: "John 4:43-45" } },
  { id: 22, group: "Beginning of Ministry", title: "Synagogue at Nazareth", refs: { matthew: NR, mark: NR, luke: "Luke 4:16-30", john: NR } },
  { id: 23, group: "Beginning of Ministry", title: "Disciples Called (Andrew, Simon, James, John)", refs: { matthew: "Matthew 4:13-22", mark: "Mark 1:16-20", luke: "Luke 5:1-11", john: NR } },
  { id: 24, group: "Galilean Ministry — Miracles", title: "Demoniac in the Synagogue Healed", refs: { matthew: NR, mark: "Mark 1:21-28", luke: "Luke 4:31-37", john: NR } },
  { id: 25, group: "Galilean Ministry — Miracles", title: "Peter's Mother-in-Law Healed", refs: { matthew: "Matthew 8:14-17", mark: "Mark 1:29-34", luke: "Luke 4:38-41", john: NR } },
  { id: 26, group: "Galilean Ministry — Miracles", title: "Healing a Leper", refs: { matthew: "Matthew 8:1-4", mark: "Mark 1:40-45", luke: "Luke 5:12-16", john: NR } },
  { id: 27, group: "Galilean Ministry — Miracles", title: "The Paralytic Healed", refs: { matthew: "Matthew 9:1-8", mark: "Mark 2:1-12", luke: "Luke 5:17-26", john: NR } },
  { id: 28, group: "Galilean Ministry — Miracles", title: "Matthew Called", refs: { matthew: "Matthew 9:9-13", mark: "Mark 2:13-17", luke: "Luke 5:27-32", john: NR } },
  { id: 29, group: "Galilean Ministry — Miracles", title: "Pool of Bethesda", refs: { matthew: NR, mark: NR, luke: NR, john: "John 5:1-47" } },
  { id: 30, group: "Sermon on the Mount", title: "The Twelve Apostles Named", refs: { matthew: "Matthew 10:2-4", mark: "Mark 3:13-19", luke: "Luke 6:12-16", john: NR } },
  { id: 31, group: "Sermon on the Mount", title: "The Sermon on the Mount / Plain", refs: { matthew: "Matthew 5:1-7:29", mark: NR, luke: "Luke 6:17-49", john: NR }, note: "Matthew records the full Sermon; Luke records a shorter parallel." },
  { id: 32, group: "Galilean Ministry — Parables & Teaching", title: "Centurion's Servant / Widow's Son at Nain", refs: { matthew: "Matthew 8:5-13", mark: NR, luke: "Luke 7:1-17", john: NR } },
  { id: 33, group: "Galilean Ministry — Parables & Teaching", title: "Messengers from John the Baptist", refs: { matthew: "Matthew 11:2-19", mark: NR, luke: "Luke 7:18-35", john: NR } },
  { id: 34, group: "Galilean Ministry — Parables & Teaching", title: "Parable of the Sower", refs: { matthew: "Matthew 13:1-23", mark: "Mark 4:1-20", luke: "Luke 8:4-15", john: NR } },
  { id: 35, group: "Galilean Ministry — Parables & Teaching", title: "Parable of the Wheat and Tares", refs: { matthew: "Matthew 13:24-30, 36-43", mark: NR, luke: NR, john: NR } },
  { id: 36, group: "Galilean Ministry — Parables & Teaching", title: "Mustard Seed / Leaven", refs: { matthew: "Matthew 13:31-33", mark: "Mark 4:30-32", luke: "Luke 13:18-21", john: NR } },
  { id: 37, group: "Galilean Ministry — Parables & Teaching", title: "Hidden Treasure / Pearl / Dragnet", refs: { matthew: "Matthew 13:44-52", mark: NR, luke: NR, john: NR } },
  { id: 38, group: "Galilean Ministry — Parables & Teaching", title: "Christ Stills the Storm", refs: { matthew: "Matthew 8:18-27", mark: "Mark 4:35-41", luke: "Luke 8:22-25", john: NR } },
  { id: 39, group: "Galilean Ministry — Parables & Teaching", title: "Gadarene Demoniacs", refs: { matthew: "Matthew 8:28-34", mark: "Mark 5:1-20", luke: "Luke 8:26-39", john: NR } },
  { id: 40, group: "Galilean Ministry — Parables & Teaching", title: "Jairus's Daughter / Woman with Issue of Blood", refs: { matthew: "Matthew 9:18-26", mark: "Mark 5:21-43", luke: "Luke 8:40-56", john: NR } },
  { id: 41, group: "Feeding Miracles & Major Events", title: "Sending Out the Twelve", refs: { matthew: "Matthew 10:5-42", mark: "Mark 6:7-13", luke: "Luke 9:1-6", john: NR } },
  { id: 42, group: "Feeding Miracles & Major Events", title: "Death of John the Baptist", refs: { matthew: "Matthew 14:3-12", mark: "Mark 6:17-29", luke: NR, john: NR } },
  { id: 43, group: "Feeding Miracles & Major Events", title: "Feeding the Five Thousand", refs: { matthew: "Matthew 14:13-21", mark: "Mark 6:30-44", luke: "Luke 9:10-17", john: "John 6:1-15" } },
  { id: 44, group: "Feeding Miracles & Major Events", title: "Walking on Water", refs: { matthew: "Matthew 14:22-33", mark: "Mark 6:45-52", luke: NR, john: "John 6:16-21" } },
  { id: 45, group: "Feeding Miracles & Major Events", title: "The Bread of Life Discourse", refs: { matthew: NR, mark: NR, luke: NR, john: "John 6:22-65" } },
  { id: 46, group: "Feeding Miracles & Major Events", title: "Peter's Confession of Faith", refs: { matthew: "Matthew 16:13-19", mark: "Mark 8:27-29", luke: "Luke 9:18-20", john: "John 6:66-71" } },
  { id: 47, group: "Feeding Miracles & Major Events", title: "The Transfiguration", refs: { matthew: "Matthew 17:1-9", mark: "Mark 9:2-10", luke: "Luke 9:28-36", john: NR }, note: "John omits the Transfiguration and focuses on Upper Room discourse unique material." },
  { id: 48, group: "Later Ministry", title: "The Good Samaritan", refs: { matthew: NR, mark: NR, luke: "Luke 10:25-37", john: NR } },
  { id: 49, group: "Later Ministry", title: "The Lord's Prayer", refs: { matthew: "Matthew 6:9-13", mark: NR, luke: "Luke 11:1-4", john: NR } },
  { id: 50, group: "Later Ministry", title: "Teaching at Feast of Tabernacles", refs: { matthew: NR, mark: NR, luke: NR, john: "John 7:1-53" } },
  { id: 51, group: "Later Ministry", title: "Woman Taken in Adultery", refs: { matthew: NR, mark: NR, luke: NR, john: "John 8:1-11" } },
  { id: 52, group: "Later Ministry", title: "The Man Born Blind", refs: { matthew: NR, mark: NR, luke: NR, john: "John 9:1-41" } },
  { id: 53, group: "Later Ministry", title: "The Good Shepherd", refs: { matthew: NR, mark: NR, luke: NR, john: "John 10:1-21" } },
  { id: 54, group: "Later Ministry", title: "Raising of Lazarus", refs: { matthew: NR, mark: NR, luke: NR, john: "John 11:1-44" } },
  { id: 55, group: "Later Ministry", title: "Zacchaeus", refs: { matthew: NR, mark: NR, luke: "Luke 19:1-10", john: NR } },
  { id: 56, group: "Later Ministry", title: "Parable of the Prodigal Son", refs: { matthew: NR, mark: NR, luke: "Luke 15:11-32", john: NR } },
  { id: 57, group: "Later Ministry", title: "Parable of the Rich Man and Lazarus", refs: { matthew: NR, mark: NR, luke: "Luke 16:19-31", john: NR } },
  { id: 58, group: "The Last Week", title: "Triumphal Entry", refs: { matthew: "Matthew 21:1-11", mark: "Mark 11:1-10", luke: "Luke 19:29-44", john: "John 12:12-19" } },
  { id: 59, group: "The Last Week", title: "Cleansing the Temple (Second)", refs: { matthew: "Matthew 21:12-16", mark: "Mark 11:15-18", luke: "Luke 19:45-48", john: NR } },
  { id: 60, group: "The Last Week", title: "The Olivet Discourse", refs: { matthew: "Matthew 24:1-51", mark: "Mark 13:1-37", luke: "Luke 21:5-36", john: NR } },
  { id: 61, group: "The Last Week", title: "The Ten Virgins / Talents / Judgment", refs: { matthew: "Matthew 25:1-46", mark: NR, luke: NR, john: NR } },
  { id: 62, group: "The Last Week", title: "The Last Supper", refs: { matthew: "Matthew 26:17-30", mark: "Mark 14:12-26", luke: "Luke 22:7-23", john: "John 13:1-35" } },
  { id: 63, group: "The Last Week", title: "Upper Room Discourse", refs: { matthew: NR, mark: NR, luke: NR, john: "John 14:1-16:33" } },
  { id: 64, group: "The Last Week", title: "High Priestly Prayer", refs: { matthew: NR, mark: NR, luke: NR, john: "John 17:1-26" } },
  { id: 65, group: "The Last Week", title: "Gethsemane", refs: { matthew: "Matthew 26:36-46", mark: "Mark 14:32-42", luke: "Luke 22:40-46", john: "John 18:1" } },
  { id: 66, group: "Betrayal and Trial", title: "The Betrayal and Arrest", refs: { matthew: "Matthew 26:47-56", mark: "Mark 14:43-52", luke: "Luke 22:47-53", john: "John 18:2-11" } },
  { id: 67, group: "Betrayal and Trial", title: "Before Annas, Caiaphas, and the Sanhedrin", refs: { matthew: "Matthew 26:57-68", mark: "Mark 14:53-65", luke: "Luke 22:54-71", john: "John 18:12-27" } },
  { id: 68, group: "Betrayal and Trial", title: "Peter's Denial", refs: { matthew: "Matthew 26:69-75", mark: "Mark 14:66-72", luke: "Luke 22:55-62", john: "John 18:15-18, 25-27" } },
  { id: 69, group: "Betrayal and Trial", title: "Trial Before Pilate and Herod", refs: { matthew: "Matthew 27:1-2, 11-26", mark: "Mark 15:1-15", luke: "Luke 23:1-25", john: "John 18:28-19:16" } },
  { id: 70, group: "Crucifixion and Burial", title: "The Crucifixion", refs: { matthew: "Matthew 27:27-56", mark: "Mark 15:16-41", luke: "Luke 23:26-49", john: "John 19:17-37" }, note: "Seven Last Words compiled across all four Gospels." },
  { id: 71, group: "Crucifixion and Burial", title: "The Burial", refs: { matthew: "Matthew 27:57-66", mark: "Mark 15:42-47", luke: "Luke 23:50-56", john: "John 19:38-42" } },
  { id: 72, group: "Resurrection and Ascension", title: "The Resurrection", refs: { matthew: "Matthew 28:1-10", mark: "Mark 16:1-11", luke: "Luke 24:1-12", john: "John 20:1-18" } },
  { id: 73, group: "Resurrection and Ascension", title: "Road to Emmaus", refs: { matthew: NR, mark: "Mark 16:12-13", luke: "Luke 24:13-35", john: NR } },
  { id: 74, group: "Resurrection and Ascension", title: "Appearances to the Disciples", refs: { matthew: NR, mark: "Mark 16:14-18", luke: "Luke 24:36-49", john: "John 20:19-29" } },
  { id: 75, group: "Resurrection and Ascension", title: "Appearance at Sea of Tiberias", refs: { matthew: NR, mark: NR, luke: NR, john: "John 21:1-23" } },
  { id: 76, group: "Resurrection and Ascension", title: "The Great Commission", refs: { matthew: "Matthew 28:16-20", mark: "Mark 16:15-18", luke: NR, john: NR } },
  { id: 77, group: "Resurrection and Ascension", title: "The Ascension", refs: { matthew: NR, mark: "Mark 16:19-20", luke: "Luke 24:50-53", john: NR } },
];

export const GOSPEL_META = {
  matthew: { label: "MATTHEW", author: "Tax collector", theme: "The King", accent: "#1a4a8a" },
  mark: { label: "MARK", author: "Peter's companion", theme: "The Servant", accent: "#8b1a1a" },
  luke: { label: "LUKE", author: "Physician", theme: "The Son of Man", accent: "#1a6b3a" },
  john: { label: "JOHN", author: "Apostle", theme: "The Son of God", accent: "#5b1a8b" },
} as const;

